# Setup

## 1. Environment Setup

We use [`uv`](https://github.com/astral-sh/uv) for fast, reproducible package management.

The steps below:
1. Install `uv` into `~/.local/bin`
2. Create a virtual environment at `.venv/`
3. Install all required packages (This might take a while)

> **After running this cell, restart the kernel** so that the newly installed packages (especially `vllm` and `transformers`) are picked up by the current Python session.

### IN Colab

In [1]:
#!unzip repo.zip -d /content/CSE151B_Kaggle

import os
os.chdir('/content/CSE151B_Kaggle/CSE151B_Kaggle')

In [2]:
!pip install prettyprint sympy numpy pandas matplotlib transformers accelerate vllm tqdm bitsandbytes ipykernel jupyter nvidia-nvjitlink antlr4-python3-runtime==4.11.1

Collecting prettyprint
  Downloading prettyprint-0.1.5.tar.gz (2.1 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (1.14.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Collecting vllm
  Downloading vllm-0.20.1-cp38-abi3-manylinux_2_35_x86_64.whl.metadata (10 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)
Collecting bitsandbytes
  Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: ipykernel in /usr/local/lib/python3.12/dist-packages (6.17.1)
Collecting jupyter
  Downloading jupyter-1.1.1-py2.py3-none-any.whl.metadata (2.0 kB)
Collecting nvidia-nvjitlink
  Downloading nvidia_nvjitlink-13.2.78-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.8 kB)
Collecting antlr4-python3-runtime==4.11.1
  Downloading antlr4_python3_runtime-4.11.1-py3-none-any.whl.metadata (291 bytes)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy) (1.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.29.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.11.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.10.0+cu128)
Requirement already satisfied: cachetools in /usr/local/lib/python3.12/dist-packages (from vllm) (6.2.6)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (from vllm) (0.2.1)
Requirement already satisfied: requests>=2.26.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (2.32.4)
Collecting blake3 (from vllm)
  Downloading blake3-1.0.8-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.6 kB)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.12/dist-packages (from vllm) (9.0.0)
Collecting transformers
  Downloading transformers-5.7.0-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: protobuf!=6.30.*,!=6.31.*,!=6.32.*,!=6.33.0.*,!=6.33.1.*,!=6.33.2.*,!=6.33.3.*,!=6.33.4.*,>=5.29.6 in /usr/local/lib/python3.12/dist-packages (from vllm) (5.29.6)
Requirement already satisfied: fastapi>=0.115.0 in /usr/local/lib/python3.12/dist-packages (from fastapi[standard]>=0.115.0->vllm) (0.136.1)
Requirement already satisfied: aiohttp>=3.13.3 in /usr/local/lib/python3.12/dist-packages (from vllm) (3.13.5)
Requirement already satisfied: openai>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (2.32.0)
Requirement already satisfied: pydantic>=2.12.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (2.12.3)
Requirement already satisfied: prometheus_client>=0.18.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.25.0)
Collecting prometheus-fastapi-instrumentator>=7.0.0 (from vllm)
  Downloading prometheus_fastapi_instrumentator-7.1.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: tiktoken>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.12.0)
Collecting lm-format-enforcer==0.11.3 (from vllm)
  Downloading lm_format_enforcer-0.11.3-py3-none-any.whl.metadata (17 kB)
Collecting llguidance<1.4.0,>=1.3.0 (from vllm)
  Downloading llguidance-1.3.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Collecting outlines_core==0.2.14 (from vllm)
  Downloading outlines_core-0.2.14-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.6 kB)
Collecting diskcache==5.6.3 (from vllm)
  Downloading diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Collecting lark==1.2.2 (from vllm)
  Downloading lark-1.2.2-py3-none-any.whl.metadata (1.8 kB)
Collecting xgrammar<1.0.0,>=0.1.32 (from vllm)
  Downloading xgrammar-0.2.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.2 kB)
Requirement already satisfied: typing_extensions>=4.10 in /usr/local/lib/python3.12/dist-packages (from vllm) (4.15.0)
Collecting partial-json-parser (from vllm)
  Downloading partial_json_parser-0.2.1.1.post7-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: pyzmq>=25.0.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (26.2.1)
Collecting msgspec (from vllm)
  Downloading msgspec-0.21.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.8 kB)
Collecting gguf>=0.17.0 (from vllm)
  Downloading gguf-0.18.0-py3-none-any.whl.metadata (4.5 kB)
Collecting mistral_common>=1.11.0 (from mistral_common[image]>=1.11.0->vllm)
  Downloading mistral_common-1.11.1-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: opencv-python-headless>=4.13.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (4.13.0.92)
Requirement already satisfied: six>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (1.17.0)
Collecting setuptools<81.0.0,>=77.0.3 (from vllm)
  Downloading setuptools-80.10.2-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (from vllm) (0.8.2)
Collecting compressed-tensors==0.15.0.1 (from vllm)
  Downloading compressed_tensors-0.15.0.1-py3-none-any.whl.metadata (4.7 kB)
Collecting depyf==0.20.0 (from vllm)
  Downloading depyf-0.20.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from vllm) (3.1.2)
Requirement already satisfied: watchfiles in /usr/local/lib/python3.12/dist-packages (from vllm) (1.1.1)
Requirement already satisfied: python-json-logger in /usr/local/lib/python3.12/dist-packages (from vllm) (4.1.0)
Collecting ninja (from vllm)
  Downloading ninja-1.13.0-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.1 kB)
Collecting pybase64 (from vllm)
  Downloading pybase64-1.4.3-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl.metadata (8.7 kB)
Collecting cbor2 (from vllm)
  Downloading cbor2-6.0.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting ijson (from vllm)
  Downloading ijson-3.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (23 kB)
Collecting setproctitle (from vllm)
  Downloading setproctitle-1.3.7-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (10 kB)
Collecting openai-harmony>=0.0.3 (from vllm)
  Downloading openai_harmony-0.0.8-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.0 kB)
Collecting anthropic>=0.71.0 (from vllm)
  Downloading anthropic-0.97.0-py3-none-any.whl.metadata (3.1 kB)
Collecting model-hosting-container-standards<1.0.0,>=0.1.13 (from vllm)
  Downloading model_hosting_container_standards-0.1.14-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: mcp in /usr/local/lib/python3.12/dist-packages (from vllm) (1.27.0)
Requirement already satisfied: opentelemetry-sdk>=1.27.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (1.38.0)
Requirement already satisfied: opentelemetry-api>=1.27.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (1.38.0)
Collecting opentelemetry-exporter-otlp>=1.27.0 (from vllm)
  Downloading opentelemetry_exporter_otlp-1.41.1-py3-none-any.whl.metadata (2.4 kB)
Collecting opentelemetry-semantic-conventions-ai>=0.4.1 (from vllm)
  Downloading opentelemetry_semantic_conventions_ai-0.5.1-py3-none-any.whl.metadata (997 bytes)
Collecting numba==0.65.0 (from vllm)
  Downloading numba-0.65.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.9 kB)
Collecting torch>=2.0.0 (from accelerate)
  Downloading torch-2.11.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (29 kB)
Collecting torchaudio==2.11.0 (from vllm)
  Downloading torchaudio-2.11.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (6.9 kB)
Collecting torchvision==0.26.0 (from vllm)
  Downloading torchvision-0.26.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting flashinfer-python==0.6.8.post1 (from vllm)
  Downloading flashinfer_python-0.6.8.post1-py3-none-any.whl.metadata (11 kB)
Collecting flashinfer-cubin==0.6.8.post1 (from vllm)
  Downloading flashinfer_cubin-0.6.8.post1-py3-none-any.whl.metadata (1.3 kB)
Collecting apache-tvm-ffi==0.1.9 (from vllm)
  Downloading apache_tvm_ffi-0.1.9-cp312-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (6.1 kB)
Collecting tilelang==0.1.9 (from vllm)
  Downloading tilelang-0.1.9-cp38-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (15 kB)
Collecting nvidia-cudnn-frontend<1.19.0,>=1.13.0 (from vllm)
  Downloading nvidia_cudnn_frontend-1.18.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (4.4 kB)
Collecting fastsafetensors>=0.2.2 (from vllm)
  Downloading fastsafetensors-0.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.0 kB)
Collecting nvidia-cutlass-dsl>=4.4.2 (from vllm)
  Downloading nvidia_cutlass_dsl-4.4.2-py3-none-any.whl.metadata (2.7 kB)
Collecting quack-kernels>=0.3.3 (from vllm)
  Downloading quack_kernels-0.4.1-py3-none-any.whl.metadata (640 bytes)
Collecting loguru (from compressed-tensors==0.15.0.1->vllm)
  Downloading loguru-0.7.3-py3-none-any.whl.metadata (22 kB)
Collecting astor (from depyf==0.20.0->vllm)
  Downloading astor-0.8.1-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from depyf==0.20.0->vllm) (0.3.8)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.8.post1->vllm) (8.3.3)
Collecting cuda-tile (from flashinfer-python==0.6.8.post1->vllm)
  Downloading cuda_tile-1.3.0-cp312-cp312-manylinux2014_x86_64.whl.metadata (7.3 kB)
Requirement already satisfied: nvidia-ml-py in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.8.post1->vllm) (13.595.45)
Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.8.post1->vllm) (0.9.0)
Collecting interegular>=0.3.2 (from lm-format-enforcer==0.11.3->vllm)
  Downloading interegular-0.3.3-py37-none-any.whl.metadata (3.0 kB)
Collecting llvmlite<0.48,>=0.47.0dev0 (from numba==0.65.0->vllm)
  Downloading llvmlite-0.47.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.0 kB)
Collecting torch-c-dlpack-ext (from tilelang==0.1.9->vllm)
  Downloading torch_c_dlpack_ext-0.1.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (14 kB)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from tilelang==0.1.9->vllm) (0.5.4)
Collecting z3-solver<4.15.5,>=4.13.0 (from tilelang==0.1.9->vllm)
  Downloading z3_solver-4.15.4.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (602 bytes)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2025.3.0)
Collecting cuda-toolkit==13.0.2 (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate)
  Downloading cuda_toolkit-13.0.2-py2.py3-none-any.whl.metadata (9.4 kB)
Collecting cuda-bindings<14,>=13.0.3 (from torch>=2.0.0->accelerate)
  Downloading cuda_bindings-13.2.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.3 kB)
Collecting nvidia-cudnn-cu13==9.19.0.56 (from torch>=2.0.0->accelerate)
  Downloading nvidia_cudnn_cu13-9.19.0.56-py3-none-manylinux_2_27_x86_64.whl.metadata (1.9 kB)
Collecting nvidia-cusparselt-cu13==0.8.0 (from torch>=2.0.0->accelerate)
  Downloading nvidia_cusparselt_cu13-0.8.0-py3-none-manylinux2014_x86_64.whl.metadata (12 kB)
Collecting nvidia-nccl-cu13==2.28.9 (from torch>=2.0.0->accelerate)
  Downloading nvidia_nccl_cu13-2.28.9-py3-none-manylinux_2_18_x86_64.whl.metadata (2.0 kB)
Collecting nvidia-nvshmem-cu13==3.4.5 (from torch>=2.0.0->accelerate)
  Downloading nvidia_nvshmem_cu13-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.1 kB)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Collecting nvidia-cublas==13.1.0.3.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate)
  Downloading nvidia_cublas-13.1.0.3-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime==13.0.96.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate)
  Downloading nvidia_cuda_runtime-13.0.96-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufft==12.0.0.61.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate)
  Downloading nvidia_cufft-12.0.0.61-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cufile==1.15.1.6.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate)
  Downloading nvidia_cufile-1.15.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti==13.0.85.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate)
  Downloading nvidia_cuda_cupti-13.0.85-py3-none-manylinux_2_25_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-curand==10.4.0.35.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate)
  Downloading nvidia_curand-10.4.0.35-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver==12.0.4.66.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate)
  Downloading nvidia_cusolver-12.0.4.66-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse==12.6.3.3.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate)
  Downloading nvidia_cusparse-12.6.3.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink
  Downloading nvidia_nvjitlink-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-nvrtc==13.0.88.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate)
  Downloading nvidia_cuda_nvrtc-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-nvtx==13.0.85.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate)
  Downloading nvidia_nvtx-13.0.85-py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl.metadata (1.8 kB)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.2)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel) (1.8.15)
Requirement already satisfied: ipython>=7.23.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel) (7.34.0)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from ipykernel) (7.4.9)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel) (0.2.1)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from ipykernel) (1.6.0)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel) (6.5.1)
Requirement already satisfied: traitlets>=5.1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel) (5.7.1)
Requirement already satisfied: notebook in /usr/local/lib/python3.12/dist-packages (from jupyter) (6.5.7)
Requirement already satisfied: jupyter-console in /usr/local/lib/python3.12/dist-packages (from jupyter) (6.6.3)
Requirement already satisfied: nbconvert in /usr/local/lib/python3.12/dist-packages (from jupyter) (7.17.1)
Requirement already satisfied: ipywidgets in /usr/local/lib/python3.12/dist-packages (from jupyter) (7.7.1)
Collecting jupyterlab (from jupyter)
  Downloading jupyterlab-4.5.7-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (1.8.0)

In [2]:
import os

# Point Colab's environment to the newly installed nvidia-nvjitlink package
lib_path = "/usr/local/lib/python3.12/dist-packages/nvidia/nvjitlink/lib"

if "LD_LIBRARY_PATH" in os.environ:
    os.environ["LD_LIBRARY_PATH"] += f":{lib_path}"
else:
    os.environ["LD_LIBRARY_PATH"] = lib_path

In [24]:
# At the end to download shit

#!rm -rf /content/CSE151B_Kaggle/.venv

!zip -r CSE151B_Kaggle.zip /content/CSE151B_Kaggle/CSE151B_Kaggle

from google.colab import files
files.download('CSE151B_Kaggle.zip')

  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/description (deflated 14%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/logs/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/logs/HEAD (deflated 71%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/logs/refs/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/logs/refs/heads/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/logs/refs/heads/main (deflated 71%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/logs/refs/remotes/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/logs/refs/remotes/origin/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/logs/refs/remotes/origin/HEAD (deflated 87%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/logs/refs/remotes/origin/main (deflated 73%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/gk/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/gk/config (deflated 32%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/FETCH_HEAD (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/HEAD (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/COMMIT_EDITMSG (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/ORIG_HEAD (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/hooks/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/hooks/update.sample (deflated 68%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/hooks/pre-merge-commit.sample (deflated 39%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/hooks/pre-rebase.sample (deflated 59%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/hooks/post-update.sample (deflated 27%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/hooks/sendemail-validate.sample (deflated 58%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/hooks/push-to-checkout.sample (deflated 55%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/hooks/fsmonitor-watchman.sample (deflated 62%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/hooks/commit-msg.sample (deflated 44%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/hooks/pre-push.sample (deflated 49%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/hooks/prepare-commit-msg.sample (deflated 50%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/hooks/pre-commit.sample (deflated 45%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/hooks/pre-receive.sample (deflated 40%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/hooks/applypatch-msg.sample (deflated 42%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/hooks/pre-applypatch.sample (deflated 38%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/refs/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/refs/heads/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/refs/heads/main (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/refs/tags/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/refs/remotes/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/refs/remotes/origin/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/refs/remotes/origin/HEAD (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/refs/remotes/origin/main (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/info/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/info/exclude (deflated 28%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/34/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/34/f15b3d016a713f0168adf66aa7ae1579fe3698 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/34/5d5f96762381ae4853bdc2209fbbc995ebee13 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/60/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/60/ad05283dd9167e038710343d529353d560dc0c (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/60/e3fea5571df2e17d19ed62b5ff6af24bf53499 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/pack/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/pack/pack-263131e2b112d5b062322756a32995c406d864eb.rev (deflated 21%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/pack/pack-263131e2b112d5b062322756a32995c406d864eb.idx (deflated 65%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/pack/pack-263131e2b112d5b062322756a32995c406d864eb.pack (deflated 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/fd/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/fd/fb280d5a0644e7b111e015e15d9692f2b7cbdf (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/bb/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/bb/e105243f389f9ae9b56914d1d6e3a84560e9cc (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/66/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/66/950a1986c72fb7d156161dadf98fe545510cd5 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/04/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/04/e8a12c20ed54885954c3605fafa3e4a17efa50 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/7a/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/7a/0bf050f1ae466b4fc7ef4fb92a8ec8816debfe (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/be/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/be/f09f506eae0e56976925d308d76bd42ed86993 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/be/129e27155ccf29c0fe3d13d100d6357426473e (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/95/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/95/3f4e47b813d1f16ca42fc4b0119dcc6dbea0a3 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/f8/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/f8/50b01d69e5258b5cfbe94aefdbfaa980a8678c (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/19/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/19/a5b13a569d73fbbc227768588ced9e5056ce4c (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/aa/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/aa/b1c30c4f60d0bbf9aea8cb3ad8ccb79f5c1b72 (deflated 2%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/68/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/68/a20cd3dde06432b6c0391ea619b09ed40e8726 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/51/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/51/96ef984c9830f8299121b87823fa2b85800545 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/b8/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/b8/f894e54aae5e0638610bc608b7d82ad66faae6 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/ea/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/ea/58251ee8484b7410ad75292a9705578c4734c1 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/a1/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/a1/293cf942ea2d0389b42b5456d2126f23340a59 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/ae/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/ae/1ea1af118c26f91fe7a8a3f686bee90d1e140b (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/e4/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/e4/5d070f9a48d4692730a2775c40312348725f97 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/e4/02775ce5c58e08803f6dd8725025cab6a66938 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/33/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/33/baa85372842ce0a732ce7a8871b3a3a992c2b6 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/0d/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/0d/93e439db95a825ad3f0e174be3a59240f3ea3e (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/43/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/43/9f4da37c76700d5a905fd6997e5b836b23414f (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/b9/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/b9/ff3174f08396e0097a5e74133cd8f7447acd72 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/7f/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/7f/d3fcac35d5445a19294ab49147befd583e2eed (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/f2/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/f2/b7cadf39c2e7fde49615b27b8f111ccb2ba972 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/d7/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/d7/16c81697abc346c62b9f518c54915d81d1658f (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/df/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/df/806266368b9de470f7c901067a05667516cfcd (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/78/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/78/a11bbe8386820d9d76e3f6dfd4994992454ee3 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/c8/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/c8/e2e80eb3068cbb4a8204848b24d7b31c273d48 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/08/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/08/a74bfb4ac27317fc49b7df9ea46b821cbc0ecf (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/08/f9ce190aae0c52805c6dc16fbcf2f4ef96c6ec (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/f9/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/f9/8f23088b7e12beb6f9e0f7081d444dcab92238 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/ee/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/ee/6fa81f1e4b209b65a9f6dafa5a1b2cfabfd8e4 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/d6/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/d6/2e02676cf865834f834e54523f710c0ce9016c (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/38/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/38/b9f09e75fdb8ab1fdc9dbb32e9a9dee639bb63 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/41/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/41/ac195ff9c64ca79e770a37346bf2d85ec5d39f (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/b4/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/b4/c6f41300b33bbe779991b48d9fcaba73992756 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/b4/bcfafe8de416fcd62a8d016dabfcd16558c038 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/b0/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/b0/996a23db460b2986b545d4803d10a756d94e18 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/ab/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/ab/8bc211853e57927017f158c0a71de5c2e61f52 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/e6/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/e6/9e82703df048ba22a79a28b1c18f57d914dacc (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/e9/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/e9/8f49e03568f6eb35a6ccf40488631bb1a95f0d (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/77/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/77/2e508aeedbf65fc5bd03b685a5db1977fac992 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/3e/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/3e/2cdb0d80b5b0c6ac0425b23a63cebef799f8c8 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/info/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/7e/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/7e/f6e57c2f2143ac8b5c377282bac14c6a97c53e (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/24/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/24/0808efa03329d07af05cbe5d636210d239961d (deflated 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/e7/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/e7/2ecab6044873777dcb8893d281faacaf3fcb91 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/2d/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/2d/18e971b3d79cf360a4b32c74bd99d1eb6fb4ae (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/45/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/45/b62f1e2c1817e79f46e0e5292a5b7161452298 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/fe/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/fe/3edc0e42cbde69199a307a7eb554433bf7d436 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/de/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/de/4c533d69319741411f89c49b1d407b51557e05 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/53/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/53/460228dd567774afc68e46011ffdadb69329b8 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/3d/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/3d/21bcfff886a557c86261631aa8d48f26e95d83 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/3d/6f187a47a78111ca5858fb3e93efbae9d39f2d (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/6b/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/6b/86ef6af8fcbf7bbe33f35bf8069fb8fb587246 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/6b/764b38502d39f787a8c4d757c50155cdaf0e2b (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/50/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/50/e5277ddb04df80d4156bdafe02da5721fd53e2 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/01/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/01/6459460dc8e3f03cde4e62473726357ede420a (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/eb/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/eb/81e5133fe7efe6a577b8a8f229a09bdcfb6fe1 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/a4/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/a4/02ea89c204aa048b9ebd89978b1fdc9695523e (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/e1/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/e1/0e2d4603fb75428753e0e13ae2da72c01e3a52 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/a0/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/a0/daf3f26f0dad16a76f6f8d27cef18bfaa3b765 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/a0/a7ad8dbaeecbd1dda1b0663948636047c39fbc (deflated 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/58/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/58/eed705f890fccf654ebd99982d97f23b4f5596 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/cc/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/cc/d7907f2984dd3fe09cd42ea85db083bf4e4991 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/d5/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/d5/072ab9530d2af246e570a86df366d348978cb0 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/15/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/15/bdf198fb31dd46a2ff7b05242451c922c3fa2d (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/3b/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/3b/0438cbafda5432b41d0a848f214bfb3e159442 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/1a/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/1a/a96412db912fcfa516b2ead9b9df695fb25fa8 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/8e/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/8e/f9240f0715e3aa00e2bac366c3d40082a0211d (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/b6/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/b6/0be45cffd3707986f1e7219b6244362283f1c6 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/93/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/93/0af5ad7bb98af59646e26e8dbbf0d65bf8bed6 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/93/5228b0218bab53073cbe6ebe9aba55b0e7fd8b (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/af/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/af/81e6e216b486e813f6e3b3fdd13da375746cd2 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/35/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/35/8e0c052527de911a425f06b414e0512a9f479c (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/cb/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/cb/84eeee53ccda53a960bbd7e74b64fa41df5949 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/69/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/69/33604e860091056aeae099db8d310705c676b4 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/91/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/91/8bedff526494255ebb895e8ae8b44bcd95d4b0 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/57/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/objects/57/46be9922ab18442fd4b4b95695c72343a06004 (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/index (deflated 40%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/packed-refs (deflated 9%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/.git/config (deflated 39%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/Runner.ipynb (deflated 92%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/prompting/ (stored 0%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/prompting/__init__.py (deflated 38%)
  adding: content/CSE151B_Kaggle/CSE151B_Kaggle/prompting/prompt_chain.py (deflated 64%)

### Only if in DataHub

In [ ]:
# Install uv
!wget -qO- https://astral.sh/uv/install.sh | sh

!export PATH="/home/ugheewala/.local/bin:$PATH"

# Create a virtual environment
!/home/ugheewala/.local/bin/uv venv .venv --seed --clear

# Install dependencies — this is fast thanks to uv's parallel resolver
!.venv/bin/python -m pip install prettyprint sympy numpy pandas matplotlib transformers accelerate vllm tqdm bitsandbytes antlr4-python3-runtime==4.11.1 ipykernel jupyter

# Install Jupyter Kernel
!.venv/bin/python -m ipykernel install --user --name cse151b --display-name "Python (cse151b)"

print("Done. Restart the kernel before proceeding.")
print("Selection process: on top right, click on current kernel '(ususally named python)' -> 'select another kernel' -> 'Jupyter Kernel' -> 'Python (cse151b)'.")

downloading uv 0.11.8 x86_64-unknown-linux-gnu
installing to /usr/local/bin
  uv
  uvx
everything's installed!
/bin/bash: line 1: /home/ugheewala/.local/bin/uv: No such file or directory
Collecting prettyprint
  Downloading prettyprint-0.1.5.tar.gz (2.1 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting sympy
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting numpy
  Using cached numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting pandas
  Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting matplotlib
  Downloading matplotlib-3.10.9-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (52 kB)
Collecting transformers
  Using cached transformers-5.7.0-py3-none-any.whl.metadata (33 kB)
Collecting accelerate
  Downloading accelerate-1.13.0-py3-none-any.whl.metadata (19 kB)
Collecting vllm
  Using cached vllm-0.20.0-cp38-abi3-manylinux_2_35_x86_64.whl.metadata (10 kB)
Collecting tqdm
  Using cached tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Collecting bitsandbytes
  Using cached bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Collecting antlr4-python3-runtime==4.11.1
  Using cached antlr4_python3_runtime-4.11.1-py3-none-any.whl.metadata (291 bytes)
ERROR: Operation cancelled by user
/content/CSE151B_Kaggle/.venv/bin/python: No module named ipykernel
Done. Restart the kernel before proceeding.
Selection process: on top right, click on current kernel '(ususally named python)' -> 'select another kernel' -> 'Jupyter Kernel' -> 'Python (cse151b)'.

In [ ]:
# !/home/<name>/.local/bin/uv pip install --python .venv/bin/python \
#     "numpy<2" \
#     "torch==2.1.2+cu118" \
#     "transformers==4.51.3" \
#     "accelerate==0.34.2" \
#     "huggingface_hub>=0.23.0" \
#     "safetensors" \
#     "sentencepiece" \
#     "tqdm" \
#     "pandas" \
#     "matplotlib" \
#     "sympy" \
#     "antlr4-python3-runtime==4.11.1" \
#     --extra-index-url https://download.pytorch.org/whl/cu118

In [ ]:
# !/home/<name>/.local/bin/uv pip install --python .venv/bin/python \
#     "nvidia-cusparse-cu11" \
#     "nvidia-cublas-cu11" \
#     "nvidia-cuda-runtime-cu11" \
#     "nvidia-cudnn-cu11"

In [ ]:
# activate venv after installation. This needs to be run everytime.
!source ./.venv/bin/activate

In [ ]:
!/home/<name>/.local/bin/uv pip install --python .venv/bin/python \
    "numpy<2" \
    "torch==2.3.1+cu121" \
    "torchvision==0.18.1+cu121" \
    "torchaudio==2.3.1+cu121" \
    --extra-index-url https://download.pytorch.org/whl/cu121

/bin/bash: line 1: name: No such file or directory

In [ ]:
!/home/<name>/.local/bin/uv pip install --python .venv/bin/python \
    "transformers==4.51.3" \
    "accelerate>=0.30.0" \
    "huggingface_hub>=0.23.0" \
    "safetensors" \
    "sentencepiece" \
    "tokenizers==0.21.4" \
    "sympy" \
    "pandas" \
    "matplotlib" \
    "tqdm" \
    "prettyprint" \
    "antlr4-python3-runtime==4.11.1" \
    "ipykernel" \
    "jupyter"

/bin/bash: line 1: name: No such file or directory

In [ ]:
!/home/<name>/.local/bin/uv pip install --python .venv/bin/python \
    "bitsandbytes==0.45.5"

/bin/bash: line 1: name: No such file or directory

## 2. Imports & Configuration

All key settings are collected in one place.  
- `DATA_PATH` — public dataset with ground-truth answers (use this to measure accuracy)
- `OUTPUT_PATH` — where per-question results will be written
- `GPU_ID` — which GPU to use (update if your machine has a different device index)
- `MAX_TOKENS` — maximum tokens the model may generate per response

In [3]:
import os
import sys
import json
import time
import csv
import subprocess
from pathlib import Path
from pprint import pprint

import pandas as pd
import numpy as np
from tqdm.auto import tqdm

# ── Configuration ─────────────────────────────────────────────────────────────
MODEL_ID    = "Qwen/Qwen3-4B-Thinking-2507"
GPU_ID      = "0"                    # CUDA_VISIBLE_DEVICES
PUBLIC_DATA_PATH   = "data/public.jsonl"
PRIVATE_DATA_PATH   = "data/private.jsonl"
OUTPUT_PATH = "results/starter_results.jsonl"

PROJECT_ROOT = Path.cwd()

RESULTS_DIR = PROJECT_ROOT / "results"
BASELINE1_DIR = RESULTS_DIR / "baseline1_weakest"
BASELINE1_DIR.mkdir(parents=True, exist_ok=True)

VAL_FRAC = 0.20
SPLIT_SEED = 414

CACHE_DIR = None
HF_HOME_DIR = None

MAX_INPUT_TOKENS = 32768 #4096
MAX_MODEL_LEN = 32768 #4096

MAX_NEW_TOKENS_SMOKE = 32768 #256
MAX_NEW_TOKENS_BASELINE = 32768 #1024

INFERENCE_BACKEND = "vllm"

BATCH_SIZE = 32
LOAD_IN_4BIT = True


MAX_TOKENS  = 32768

os.environ["CUDA_VISIBLE_DEVICES"] = GPU_ID

if HF_HOME_DIR is not None:
    os.environ["HF_HOME"] = str(HF_HOME_DIR)

if CACHE_DIR is not None:
    Path(CACHE_DIR).mkdir(parents=True, exist_ok=True)

print("HF_HOME      :", os.environ.get("HF_HOME"))
print("HF_HUB_CACHE :", os.environ.get("HF_HUB_CACHE"))
print("cache_dir    :", CACHE_DIR)

HF_HOME      : None
HF_HUB_CACHE : None
cache_dir    : None

In [4]:
import torch

print(f"CUDA_VISIBLE_DEVICES (Env): {os.environ.get('CUDA_VISIBLE_DEVICES')}")

cuda_available = torch.cuda.is_available()
print(f"Is CUDA available? {cuda_available}")

if cuda_available:
    print(f"Current Device: {torch.cuda.current_device()}")
    print(f"Device Name: {torch.cuda.get_device_name(0)}")
    device = torch.device("cuda")
else:
    print("PyTorch still can't see the GPU.")
    device = torch.device("cpu")

CUDA_VISIBLE_DEVICES (Env): 0
Is CUDA available? True
Current Device: 0
Device Name: NVIDIA A100-SXM4-80GB

In [5]:
# import site

# roots = [Path(p) for p in site.getsitepackages()]
# matches = []

# for root in roots:
#     if root.exists():
#         matches.extend(root.rglob("libcusparse.so*"))

# for m in matches:
#     print(m)

In [6]:
# wanted_libs = {
#     "libcusparse.so",
#     "libcublas.so",
#     "libcudart.so",
#     "libcudnn.so",
# }

# lib_dirs = []

# for root in map(Path, site.getsitepackages()):
#     if not root.exists():
#         continue

#     for lib in wanted_libs:
#         for match in root.rglob(lib + "*"):
#             lib_dir = str(match.parent)
#             if lib_dir not in lib_dirs:
#                 lib_dirs.append(lib_dir)

# VENV = Path("/home/ugheewala/private/CSE151B_Kaggle/.venv")
# SITE = VENV / "lib/python3.11/site-packages"

# cuda11_dirs = [
#     SITE / "nvidia/cusparse/lib",
#     SITE / "nvidia/cublas/lib",
#     SITE / "nvidia/cuda_runtime/lib",
#     SITE / "nvidia/cudnn/lib",
#     SITE / "torch/lib",
# ]

# cuda11_dirs = [str(p) for p in cuda11_dirs if p.exists()]

# path_line = ":".join(cuda11_dirs)

# print("Add this before starting the notebook/kernel:")
# print(f'export LD_LIBRARY_PATH="{path_line}:$LD_LIBRARY_PATH"')

In [7]:
# import os
# import subprocess
# from pathlib import Path

# VENV = Path("/home/ugheewala/private/CSE151B_Kaggle/.venv")
# SITE = VENV / "lib/python3.11/site-packages"

# cuda11_dirs = [
#     SITE / "nvidia/cusparse/lib",
#     SITE / "nvidia/cublas/lib",
#     SITE / "nvidia/cuda_runtime/lib",
#     SITE / "nvidia/cudnn/lib",
#     SITE / "torch/lib",
# ]

# env = os.environ.copy()
# env["LD_LIBRARY_PATH"] = ":".join(str(p) for p in cuda11_dirs if p.exists()) + ":" + env.get("LD_LIBRARY_PATH", "")

# subprocess.run(
#     [str(VENV / "bin/python"), "-m", "bitsandbytes"],
#     env=env,
# )

In [8]:
# import json
# from pathlib import Path

# kernel_json = Path("/home/ugheewala/.local/share/jupyter/kernels/cse151b/kernel.json")

# with open(kernel_json, "r") as f:
#     spec = json.load(f)

# ld_library_path = (
#     "/home/ugheewala/private/CSE151B_Kaggle/.venv/lib/python3.11/site-packages/nvidia/cusparse/lib:"
#     "/home/ugheewala/private/CSE151B_Kaggle/.venv/lib/python3.11/site-packages/nvidia/cublas/lib:"
#     "/home/ugheewala/private/CSE151B_Kaggle/.venv/lib/python3.11/site-packages/nvidia/cuda_runtime/lib:"
#     "/home/ugheewala/private/CSE151B_Kaggle/.venv/lib/python3.11/site-packages/nvidia/cudnn/lib:"
#     "/home/ugheewala/private/CSE151B_Kaggle/.venv/lib/python3.11/site-packages/torch/lib:"
#     "${LD_LIBRARY_PATH}"
# )

# spec.setdefault("env", {})
# spec["env"]["LD_LIBRARY_PATH"] = ld_library_path
# spec["env"]["BNB_CUDA_VERSION"] = "118"

# with open(kernel_json, "w") as f:
#     json.dump(spec, f, indent=2)

# print(kernel_json)
# print(json.dumps(spec, indent=2))

In [9]:
import transformers

print("torch:", torch.__version__)
print("cuda:", torch.version.cuda)
print("cuda available:", torch.cuda.is_available())
print("transformers:", transformers.__version__)

torch: 2.11.0+cu130
cuda: 13.0
cuda available: True
transformers: 5.7.0

In [10]:
try:
    import bitsandbytes as bnb
    print("bitsandbytes:", bnb.__version__)
except Exception as e:
    print("bitsandbytes import failed:", repr(e))

ERROR:bitsandbytes.cextension:bitsandbytes library load error: libnvJitLink.so.13: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/bitsandbytes/cextension.py", line 320, in <module>
    lib = get_native_library()
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/bitsandbytes/cextension.py", line 298, in get_native_library
    dll = ct.cdll.LoadLibrary(str(binary_path))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ctypes/__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libnvJitLink.so.13: cannot open shared object file: No such file or directory

bitsandbytes: 0.49.2

In [11]:
from transformers.utils import is_torch_available, is_bitsandbytes_available

print("is_torch_available:", is_torch_available())
print("is_bitsandbytes_available:", is_bitsandbytes_available())

is_torch_available: True
is_bitsandbytes_available: True

In [12]:
from transformers import AutoTokenizer
from vllm import LLM, SamplingParams
from tqdm import tqdm

from baseline.datasets import load_public_splits, load_private_set
from baseline.generation import GenerationConfig
from baseline.prompt_sets import build_prompt_texts
from baseline.modeling import ModelConfig, load_transformers_model, predownload_model, load_model, detect_gpu_info
from baseline.scoring import load_judger, score_one, summarize_results
from baseline.progress_viz import RunProgressDashboard
from prompting.prompt_chain import build_prompt_chain
from baseline.runner import run_problem_set, benchmark_batch_sizes

In [13]:
gpu_info = detect_gpu_info()
pprint(gpu_info.to_dict())

{'capability': (8, 0),
 'cuda_available': True,
 'device_count': 1,
 'device_name': 'NVIDIA A100-SXM4-80GB'}

## 3. Load the Dataset

The dataset is stored as newline-delimited JSON (`.jsonl`). Each line is one question with the following fields:

| Field | Description |
|---|---|
| `id` | Unique question identifier |
| `question` | Problem statement |
| `options` | List of answer choices - present for **MCQ**, absent for **free-form** |
| `answer` | Ground-truth answer (letter for MCQ, value/list for free-form) |

In [14]:
splits = load_public_splits(PUBLIC_DATA_PATH, val_frac=VAL_FRAC, seed=SPLIT_SEED)

train_set = splits["train"]
val_set = splits["val"]
public_set = splits["public"]
private_set = load_private_set(PRIVATE_DATA_PATH)

print("Train summary:")
pprint(train_set.summary())

print("\nValidation summary:")
pprint(val_set.summary())

print("\nPublic summary:")
pprint(public_set.summary())

print("\nPrivate summary:")
pprint(private_set.summary())

Train summary:
{'n': 901,
 'n_answered': 901,
 'n_free_form': 601,
 'n_mcq': 300,
 'name': 'public_train'}

Validation summary:
{'n': 225,
 'n_answered': 225,
 'n_free_form': 150,
 'n_mcq': 75,
 'name': 'public_val'}

Public summary:
{'n': 1126,
 'n_answered': 1126,
 'n_free_form': 751,
 'n_mcq': 375,
 'name': 'public'}

Private summary:
{'n': 943, 'n_answered': 0, 'n_free_form': 643, 'n_mcq': 300, 'name': 'private'}

In [15]:
prompt_chain = build_prompt_chain(strategy_name="baseline")

for label, problem_set in [("train", train_set), ("val", val_set), ("private", private_set)]:
    problem = problem_set.problems()[0]
    spec = prompt_chain.build_spec(problem)

    print("=" * 80)
    print(label, "id=", problem.id, "template=", spec.name)
    print("metadata:", spec.metadata)
    print("generation_hints:", spec.generation_hints)
    print(spec.to_messages()[0]["content"][:300])
    print("--- user ---")
    print(spec.to_messages()[-1]["content"][:500])

================================================================================
train id= 499 template= baseline_mcq
metadata: {'answer_format': 'mcq', 'strategy_name': 'baseline', 'route_name': 'mcq', 'tags': []}
generation_hints: {'temperature': 0.6, 'top_p': 0.95}
You are an expert mathematician. Read the problem and the answer choices below, then select the single best answer. Output only the letter of your chosen option inside \boxed{}, e.g. \boxed{C}.
--- user ---
We now define an algorithm: The definition of a(n) is the least odd number k such that k * 2^n + 1 is a prime number. Given the input x_list (a series of values): [70, 71, 72, 73, 74, 75, 76, 77, 78, 79], determine the corresponding output sequence y_list.

Answer choices:
A. [44, 43, 129, 26, 63, 1, 90, 33, 22, 243]
B. [37, 35, 122, 19, 64, 10, 96, 26, 20, 245]
C. [38, 40, 128, 22, 71, 3, 91, 28, 14, 248]
D. [43, 37, 125, 21, 70, 9, 98, 27, 13, 246]
E. [39, 39, 127, 23, 67, 5, 93, 29, 15, 249]

================================================================================
val id= 990 template= baseline_free_form
metadata: {'answer_format': 'free_form', 'strategy_name': 'baseline', 'route_name': 'free_form', 'tags': []}
generation_hints: {'temperature': 0.6, 'top_p': 0.95}
You are an expert mathematician. Solve the problem step-by-step. Put your final answer inside \boxed{}. If the problem has multiple sub-answers, separate them by commas inside a single \boxed{}, e.g. \boxed{3, 7}.
--- user ---
A hot brick is removed from a kiln at $250^{\circ}$ C above room temperature. Over time, the brick cools off. After 2 hours have elapsed, the brick is $20^{\circ}$ C above room temperature. Let $t$ be the time in hours since the brick was removed from the kiln. Let $y=H(t)$ be the difference between the brick's and the room's temperature at time $t$. Assume that $H(t)$ is an exponential function.
(a) Find a formula for $H(t)$. $H(t)=$ [ANS]. (b) How many degrees does the brick's temperature drop
================================================================================
private id= 0 template= baseline_free_form
metadata: {'answer_format': 'free_form', 'strategy_name': 'baseline', 'route_name': 'free_form', 'tags': []}
generation_hints: {'temperature': 0.6, 'top_p': 0.95}
You are an expert mathematician. Solve the problem step-by-step. Put your final answer inside \boxed{}. If the problem has multiple sub-answers, separate them by commas inside a single \boxed{}, e.g. \boxed{3, 7}.
--- user ---
Use the order of operations to simplify: a) $[13-(11-11)]-[8-(5-6)]=$ [ANS]
b) $4 \cdot 3-2+2 \cdot 3=$ [ANS]

## 4. Modeling

In [16]:
model_config = ModelConfig(
    model_id=MODEL_ID,
    backend=INFERENCE_BACKEND,
    cache_dir=CACHE_DIR,
    gpu_id=GPU_ID,
    max_input_tokens=MAX_INPUT_TOKENS,
    max_model_len=MAX_MODEL_LEN,
    dtype="bfloat16",
    torch_dtype="bfloat16",
    load_in_4bit=False,
    device_map="auto",
    low_cpu_mem_usage=True,
    gpu_memory_utilization=0.85,
    max_num_seqs=256,
    max_num_batched_tokens=32768,
    reuse_loaded=True,
)

t0 = time.perf_counter()
model_bundle = load_model(model_config)
print(f"Model load/reuse time: {time.perf_counter() - t0:.2f} sec")
print("Backend:", model_bundle.backend)
print("Device:", model_bundle.device())

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

INFO 05-04 03:00:56 [utils.py:233] non-default args: {'trust_remote_code': True, 'dtype': 'bfloat16', 'max_model_len': 32768, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.85, 'max_num_batched_tokens': 32768, 'max_num_seqs': 256, 'disable_log_stats': True, 'model': 'Qwen/Qwen3-4B-Thinking-2507'}

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

INFO 05-04 03:00:56 [model.py:555] Resolved architecture: Qwen3ForCausalLM
INFO 05-04 03:00:56 [model.py:1680] Using max model len 32768
INFO 05-04 03:00:56 [scheduler.py:239] Chunked prefill is enabled with max_num_batched_tokens=32768.
INFO 05-04 03:00:56 [vllm.py:840] Asynchronous scheduling is enabled.
INFO 05-04 03:00:56 [kernel.py:205] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'])
WARNING 05-04 03:00:59 [system_utils.py:157] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
Model load/reuse time: 47.21 sec
Backend: vllm
Device: vllm

# Baseline 1: Naive

In [26]:
baseline1_prompt_chain = build_prompt_chain(strategy_name="baseline")

smoke_generation_config = GenerationConfig(
    max_new_tokens=MAX_NEW_TOKENS_SMOKE,
    temperature=0.6,
    top_p=0.95,
    top_k=20,
    min_p=0.0,
    repetition_penalty=1.0,
    presence_penalty=0.0,
    do_sample=True,
)

baseline1_generation_config = GenerationConfig(
    max_new_tokens=MAX_NEW_TOKENS_BASELINE,
    temperature=0.6,
    top_p=0.95,
    top_k=20,
    min_p=0.0,
    repetition_penalty=1.0,
    presence_penalty=0.0,
    do_sample=True,
)

In [ ]:
batch_report = benchmark_batch_sizes(
    problem_set=train_set,
    model_bundle=model_bundle,
    batch_sizes=[1, 2, 4, 8, 16, 32, 64],
    prompt_chain=baseline1_prompt_chain,
    generation_config=smoke_generation_config,
    sample_size=16,
    score=False,
    show_progress=False,
)

pd.DataFrame(batch_report["rows"])

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/2 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/2 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/2 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/2 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/2 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/2 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/2 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/2 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/2 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/2 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/2 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/2 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/2 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/2 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/2 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/2 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/4 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/4 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/4 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/4 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/4 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/4 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/4 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/4 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/8 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/8 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/8 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/8 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/16 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/16 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/16 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/16 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/16 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/16 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

,batch_size,ok,elapsed_sec,sec_per_problem,generation_sec_per_problem,error
0,1,True,31.408623,1.963039,1.961678,None
1,2,True,16.194406,1.012150,1.012045,None
2,4,True,8.465179,0.529074,0.528974,None
3,8,True,13.673946,0.854622,0.854519,None
4,16,True,2.361134,0.147571,0.147469,None
5,32,True,2.359985,0.147499,0.147399,None
6,64,True,2.360521,0.147533,0.147428,None

In [27]:
# Train split smoke run

baseline1_train_result = run_problem_set(
    problem_set=train_set,
    model_bundle=model_bundle,
    prompt_chain=baseline1_prompt_chain,
    generation_config=baseline1_generation_config,
    batch_size=BATCH_SIZE,
    limit=32,
    score=True,
    output_jsonl_path=BASELINE1_DIR / "train_results.jsonl",
    report_json_path=BASELINE1_DIR / "train_report.json",
)

pprint(baseline1_train_result.report)

Generating:   0%|          | 0/1 [00:00<?, ?it/s]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

{'backend': 'vllm',
 'batch_size': 32,
 'generation': {'backend': 'vllm',
                'batch_size': 32,
                'elapsed_sec': 461.6509095460001,
                'max_new_tokens': 32768,
                'n': 32,
                'responses': ["Okay, let's try to figure out this problem step "
                              'by step. So, the problem defines a(n) as the '
                              'least odd number k such that k * 2^n + 1 is a '
                              'prime number. Then we have to find the output '
                              'sequence y_list corresponding to the input '
                              'x_list [70, 71, 72, 73, 74, 75, 76, 77, 78, '
                              '79]. Each element in x_list is probably n, and '
                              'we need to compute a(n) for each n from 70 to '
                              '79.\n'
                              '\n'
                              'Wait, hold on. Wait, the problem says "the '
                              'definition of a(n) is the least odd number k '
                              'such that k * 2^n + 1 is a prime number." So '
                              'for each n, we have to find the smallest odd k '
                              'where k*2^n +1 is prime. Then the input x_list '
                              'is [70,71,...,79], so each x is n, and y_list '
                              'is the corresponding a(n) for each n.\n'
                              '\n'
                              'But the answer choices are sequences of '
                              'numbers. Let me check the answer choices. For '
                              'example, option A starts with [44, 43, 129, 26, '
                              '...], so for n=70, a(70)=44; n=71, a(71)=43; '
                              'etc. So we need to compute a(n) for n=70 to '
                              '79.\n'
                              '\n'
                              'Hmm, this seems a bit tricky because n is large '
                              '(70 to 79). I remember that numbers of the form '
                              'k*2^n +1 are known in number theory, especially '
                              'in the context of Proth primes. A Proth prime '
                              'is a prime number of the form k*2^n +1 where k '
                              'is odd and k < 2^n. So this problem is about '
                              'finding the smallest k (odd) such that k*2^n +1 '
                              'is prime, which would be the Proth prime for '
                              'that n.\n'
                              '\n'
                              'But computing this for n=70 to 79 might be '
                              "difficult manually. Wait, but maybe there's a "
                              'pattern or some known values?\n'
                              '\n'
                              'Alternatively, perhaps the problem is designed '
                              'such that the answer choices have some '
                              'structure, and we can deduce the correct one by '
                              'looking for certain properties.\n'
                              '\n'
                              "Let me think. Let's take a small n first to see "
                              'if I can get a sense. For example, take n=1. '
                              'Then we need the least odd k where k*2 +1 is '
                              "prime. Let's see: k=1: 3 (prime), so a(1)=1. "
                              'For n=2: k*4 +1 prime. k=1: 5 (prime), so '
                              'a(2)=1. Wait, but maybe for higher n?\n'
                              '\n'
                              'Wait, but the problem here is n from 70 to 79. '
                              'Hmm. Maybe the key is that for each n, a(n) is '
                              'the smallest odd k such that k*2^n +1 is prime. '
                              'So, k must be odd, so k=1,3,5,...\n'
                              '\n'
                              "Let's think about k=1 first. If 2^n +1 is "
                              'prime, then a(n)=1. But 2^n +1 is prime only '
                              'for n a power of 2 (Fermat primes). Fermat '
                              'primes are 3,5,17,257,65537. So for n=1 (2^1 '
                              '+1=3), n=2 (5), n=4 (17), n=8 (257), n=16 '
                              '(65537), etc. So for n not a power of 2, 2^n +1 '
                              'is composite. Therefore, for n not a power of '
                              '2, a(n) would be greater than 1.\n'
                              '\n'
                              'But in our problem, n ranges from 70 to 79, '
                              'which are all larger than 16, so 2^n +1 is '
                              'definitely composite. So for all these n, a(n) '
                              'must be at least 3.\n'
                              '\n'
                              'Wait, but the answer choices have numbers like '
                              '1 in some options. For example, option A has 1 '
                              'as the 6th element (since the list starts at 70 '
                              "as first element). Let's index the answer "
                              'choices:\n'
                              '\n'
                              'The input x_list is '
                              '[70,71,72,73,74,75,76,77,78,79], so y_list '
                              'should have 10 elements.\n'
                              '\n'
                              'Looking at the answer choices:\n'
                              '\n'
                              'A: [44,43,129,26,63,1,90,33,22,243] → 6th '
                              'element is 1 (n=75)\n'
                              '\n'
                              'B: [37,35,122,19,64,10,96,26,20,245] → 6th '
                              'element is 10\n'
                              '\n'
                              'C: [38,40,128,22,71,3,91,28,14,248] → 6th '
                              'element is 3\n'
                              '\n'
                              'D: [43,37,125,21,70,9,98,27,13,246] → 6th '
                              'element is 9\n'
                              '\n'
                              'E: [39,39,127,23,67,5,93,29,15,249] → 6th '
                              'element is 5\n'
                              '\n'
                              'F: [45,44,124,18,62,8,99,32,21,244] → 6th '
                              'element is 8\n'
                              '\n'
                              'G: [41,42,131,24,69,7,95,31,17,251] → 6th '
                              'element is 7\n'
                              '\n'
                              'H: [42,41,131,25,68,6,92,30,16,250] → 6th '
                              'element is 6\n'
                              '\n'
                              'I: [36,36,123,20,65,2,94,25,19,252] → 6th '
                              'element is 2\n'
                              '\n'
                              'J: [40,38,126,24,66,4,97,30,18,247] → 6th '
                              'element is 4\n'
                              '\n'
                              'Hmm, so the sixth element corresponds to n=75 '
                              '(since the list starts at n=70 as first '
                              "element). So for n=75, what's a(75)?\n"
                              '\n'
                              'But how can we figure this out without '
                              "computation? Maybe there's a pattern in the "
                              "answer choices. Let's see.\n"
                              '\n'
                              'Another thought: The problem states "least odd '
                              'number k". So k must be odd, so k=1,3,5,7,...\n'
                              '\n'
                              'For each n, we need to find the smallest odd k '
                              'such that k*2^n +1 is prime.\n'
                              '\n'
                              "Let's consider that k*2^n +1 = prime. Let's "
                              'denote this as p = k*2^n +1.\n'
                              '\n'
                              'So k = (p -1)/2^n. Since k must be integer and '
                              'odd.\n'
                              '\n'
                              'We need the smallest odd k, so the smallest p '
                              'of the form k*2^n +1 (prime) with k odd.\n'
                              '\n'
                              'Alternatively, for each n, we can think of k '
                              'starting from 1,3,5,... and check if (k*2^n +1) '
                              'is prime.\n'
                              '\n'
                              'But doing this for n=70 to 79 manually is '
                              "time-consuming. Maybe there's a different "
                              'approach.\n'
                              '\n'
                              'Wait, perhaps the answer choices have some '
                              'relation to n. For example, in some choices, '
                              'the numbers are related to n mod something.\n'
                              '\n'
                              'Alternatively, maybe the problem is designed '
                              'such that a(n) = (some function of n). Wait, '
                              'but given that the answer choices are specific, '
                              'perhaps we can look for a pattern in the '
                              'choices.\n'
                              '\n'
                              'Let me check option E: '
                              '[39,39,127,23,67,5,93,29,15,249]. Hmm, 127 is a '
                              "prime number (it's a Mersenne prime: 2^7 -1 "
                              '=127). Not sure.\n'
                              '\n'
                              'Wait, another angle: For a given n, the minimal '
                              "k such that k*2^n +1 is prime. Let's think "
                              'about small n.\n'
                              '\n'
                              'For example, n=3: k*8 +1. k=1:9 (not prime), '
                              'k=3:25 (nope), k=5:41 (prime). So a(3)=5.\n'
                              '\n'
                              'But not sure.\n'
                              '\n'
                              'Alternatively, maybe the problem is related to '
                              'the fact that for n even, 2^n is a square, but '
                              'not sure.\n'
                              '\n'
                              "Wait, here's an idea. In some contexts, the "
                              'minimal k for such primes might relate to the '
                              "Wieferich primes or other primes, but I don't "
                              'recall.\n'
                              '\n'
                              'Alternatively, perhaps the problem is designed '
                              'so that the answer choices have numbers that '
                              'are multiples of certain numbers or follow a '
                              'pattern.\n'
                              '\n'
                              'Looking at the answer choices, each has 10 '
                              "numbers. Let's check the numbers in each "
                              'option.\n'
                              '\n'
                              'Option A: [44,43,129,26,63,1,90,33,22,243]\n'
                              '\n'
                              'Notice that 243 is 3^5. 129 is 3*43. 63 is 7*9. '
                              'Not sure.\n'
                              '\n'
                              'Option B: [37,35,122,19,64,10,96,26,20,245] → '
                              '245=5*49=5*7².\n'
                              '\n'
                              'Option C: [38,40,128,22,71,3,91,28,14,248] → '
                              '128 is 2^7.\n'
                              '\n'
                              'Option D: [43,37,125,21,70,9,98,27,13,246] → '
                              '125=5^3.\n'
                              '\n'
                              'Option E: [39,39,127,23,67,5,93,29,15,249] → '
                              '127 is prime.\n'
                              '\n'
                              'Option F: [45,44,124,18,62,8,99,32,21,244] → '
                              '124=4*31.\n'
                              '\n'
                              'Option G: [41,42,131,24,69,7,95,31,17,251] → '
                              '251 is prime.\n'
                              '\n'
                              'Option H: [42,41,131,25,68,6,92,30,16,250] → '
                              '250=2*5^3.\n'
                              '\n'
                              'Option I: [36,36,123,20,65,2,94,25,19,252] → '
                              '123=3*41.\n'
                              '\n'
                              'Option J: [40,38,126,24,66,4,97,30,18,247] → '
                              '247=13*19.\n'
                              '\n'
                              "Hmm. Let's see. For example, option C has 128, "
                              'which is 2^7. 128 is k*2^n +1? Not sure.\n'
                              '\n'
                              'Wait, another idea: If we consider that for '
                              'each n, a(n) might be related to n in some way. '
                              'For instance, if the minimal k is such that k = '
                              '(p -1)/2^n, where p is a prime. So if we take p '
                              'as a prime that is 1 mod 2^n.\n'
                              '\n'
                              'But this is vague.\n'
                              '\n'
                              "Wait, here's a different approach. Let's "
                              'consider that the problem might be a trick '
                              'question. The definition says "the least odd '
                              'number k". So k must be odd. So k=1,3,5,...\n'
                              '\n'
                              "Let's take n=70. We need the smallest odd k "
                              'where k*2^70 +1 is prime.\n'
                              '\n'
                              'But 2^70 is a huge number. The number k*2^70 +1 '
                              'would be enormous. Finding such a prime '
                              'manually is impossible. Therefore, there must '
                              'be a pattern or a different interpretation.\n'
                              '\n'
                              'Wait a second. Wait, maybe the problem is '
                              'misstated? Or perhaps "a(n)" is defined '
                              'differently. Let me re-read the problem.\n'
                              '\n'
                              '"We now define an algorithm: The definition of '
                              'a(n) is the least odd number k such that k * '
                              '2^n + 1 is a prime number."\n'
                              '\n'
                              "Ah! Wait, maybe it's k * 2^n + 1 is prime, but "
                              'n is the input? Wait, the problem says: "Given '
                              'the input x_list (a series of values): [70, 71, '
                              '72, 73, 74, 75, 76, 77, 78, 79], determine the '
                              'corresponding output sequence y_list."\n'
                              '\n'
                              'So each x in x_list is n, and y_list is a(x) '
                              'for each x.\n'
                              '\n'
                              'But given that n is 70-79, which are large, and '
                              'the answer choices have numbers like 1,2,3,... '
                              "up to 250, it's unlikely that we can compute "
                              'this directly.\n'
                              '\n'
                              'Wait, perhaps the problem is in reverse? Like, '
                              'the output y_list is the n values for a given '
                              'k? No, the problem states: "the definition of '
                              'a(n) is the least odd number k such that k * '
                              '2^n + 1 is a prime number". So a(n) = k.\n'
                              '\n'
                              'Wait, maybe the problem is from a specific '
                              'context where these values are known. For '
                              'example, in the context of the Sierpiński '
                              'numbers or Proth primes.\n'
                              '\n'
                              'Proth primes are primes of the form k*2^n +1 '
                              'with k odd and k < 2^n. The smallest such k for '
                              "a given n is called the Proth prime's k.\n"
                              '\n'
                              "But I don't recall specific values for n=70 to "
                              '79.\n'
                              '\n'
                              'Alternatively, perhaps the problem uses a '
                              'different definition. Wait, the problem says '
                              '"least odd number k", so k must be odd, so '
                              'k=1,3,5,...\n'
                              '\n'
                              'But for some n, k=1 might work (if 2^n +1 is '
                              'prime), but as we said earlier, 2^n +1 is prime '
                              'only for n a power of 2. Since 70-79 are not '
                              "powers of 2, k=1 won't work. So a(n) must be at "
                              'least 3.\n'
                              '\n'
                              'Looking at the answer choices, the sixth '
                              'element (n=75) has various numbers: option A '
                              'has 1, which is impossible (since 2^75 +1 is '
                              'composite), so option A is invalid. Similarly, '
                              'option I has 2 as the sixth element (n=75), but '
                              'k must be odd, so 2 is even. So option I is '
                              'invalid. Option J has 4 (even), so invalid. '
                              'Similarly, options with even numbers in the '
                              'list (except maybe the first few) might be '
                              'invalid.\n'
                              '\n'
                              'Wait, important point: k must be odd. So all '
                              "elements in y_list must be odd numbers. Let's "
                              'check the answer choices.\n'
                              '\n'
                              'Option A: [44,43,129,26,63,1,90,33,22,243]. 44 '
                              '(even), 26 (even), 90 (even), 22 (even). So '
                              'multiple evens. So A is invalid.\n'
                              '\n'
                              'Option B: [37,35,122,19,64,10,96,26,20,245]. '
                              '122,64,10,96,26,20 are even. So multiple evens. '
                              'Invalid.\n'
                              '\n'
                              'Option C: [38,40,128,22,71,3,91,28,14,248]. All '

In [ ]:
"""
'generation_config': {'do_sample': True,
                       'max_new_tokens': 1024,
                       'min_p': 0.0,
                       'presence_penalty': 0.0,
                       'repetition_penalty': 1.0,
                       'temperature': 0.6,
                       'top_k': 20,
                       'top_p': 0.95},
 'output_jsonl_path': '/content/CSE151B_Kaggle/results/baseline1_weakest/train_results.jsonl',
 'problem_set': {'n': 32,
                 'n_answered': 32,
                 'n_free_form': 13,
                 'n_mcq': 19,
                 'name': 'public_train_head32'},
 'score_available': True,
 'submission_csv_path': None,
 'summary': {'free_form_acc': 0.3076923076923077,
             'mcq_acc': 0.05263157894736842,
             'n_correct': 5,
             'n_free_form': 13,
             'n_mcq': 19,
             'n_scored': 32,
             'overall_acc': 0.15625},
 'timings': {'generation_sec': 11.5697886199996,
             'prompt_build_sec': 0.002926810000644764,
             'scoring_sec': 0.7455679300001066}}
"""

In [ ]:
"""
'generation_config': {'do_sample': True,
                       'max_new_tokens': 32768,
                       'min_p': 0.0,
                       'presence_penalty': 0.0,
                       'repetition_penalty': 1.0,
                       'temperature': 0.6,
                       'top_k': 20,
                       'top_p': 0.95},
 'output_jsonl_path': '/content/CSE151B_Kaggle/CSE151B_Kaggle/results/baseline1_weakest/train_results.jsonl',
 'problem_set': {'n': 32,
                 'n_answered': 32,
                 'n_free_form': 13,
                 'n_mcq': 19,
                 'name': 'public_train_head32'},
 'score_available': True,
 'submission_csv_path': None,
 'summary': {'free_form_acc': 0.6923076923076923,
             'mcq_acc': 0.7368421052631579,
             'n_correct': 23,
             'n_free_form': 13,
             'n_mcq': 19,
             'n_scored': 32,
             'overall_acc': 0.71875},
 'timings': {'generation_sec': 461.65091967599983,
             'prompt_build_sec': 0.0029734310001003905,
             'scoring_sec': 1.0903050570000232}}
"""

In [28]:
# Validation run

baseline1_val_result = run_problem_set(
    problem_set=val_set,
    model_bundle=model_bundle,
    prompt_chain=baseline1_prompt_chain,
    generation_config=baseline1_generation_config,
    batch_size=BATCH_SIZE,
    limit=None,
    score=True,
    output_jsonl_path=BASELINE1_DIR / "val_results.jsonl",
    report_json_path=BASELINE1_DIR / "val_report.json",
)

pprint(baseline1_val_result.report)

Generating:   0%|          | 0/8 [00:00<?, ?it/s]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

KeyboardInterrupt:

In [ ]:
"""
 'generation_config': {'do_sample': True,
                       'max_new_tokens': 1024,
                       'min_p': 0.0,
                       'presence_penalty': 0.0,
                       'repetition_penalty': 1.0,
                       'temperature': 0.6,
                       'top_k': 20,
                       'top_p': 0.95},
 'output_jsonl_path': '/content/CSE151B_Kaggle/results/baseline1_weakest/val_results.jsonl',
 'problem_set': {'n': 225,
                 'n_answered': 225,
                 'n_free_form': 150,
                 'n_mcq': 75,
                 'name': 'public_val'},
 'score_available': True,
 'submission_csv_path': None,
 'summary': {'free_form_acc': 0.12666666666666668,
             'mcq_acc': 0.08,
             'n_correct': 25,
             'n_free_form': 150,
             'n_mcq': 75,
             'n_scored': 225,
             'overall_acc': 0.1111111111111111},
 'timings': {'generation_sec': 87.61873525499959,
             'prompt_build_sec': 0.01957373799996276,
             'scoring_sec': 7.864173332000064}}
"""

In [ ]:
# Test run

PRIVATE_LIMIT = None

baseline1_private_result = run_problem_set(
    problem_set=private_set,
    model_bundle=model_bundle,
    prompt_chain=baseline1_prompt_chain,
    generation_config=baseline1_generation_config,
    batch_size=BATCH_SIZE,
    limit=None,
    score=False,
    output_jsonl_path=BASELINE1_DIR / "private_results.jsonl",
    submission_csv_path=BASELINE1_DIR / "submission.csv",
    report_json_path=BASELINE1_DIR / "private_report.json",
)

pprint(baseline1_private_result.report)

In [ ]:
"""
'generation_config': {'do_sample': True,
                       'max_new_tokens': 1024,
                       'min_p': 0.0,
                       'presence_penalty': 0.0,
                       'repetition_penalty': 1.0,
                       'temperature': 0.6,
                       'top_k': 20,
                       'top_p': 0.95},
 'output_jsonl_path': '/content/CSE151B_Kaggle/results/baseline1_weakest/private_results.jsonl',
 'problem_set': {'n': 943,
                 'n_answered': 0,
                 'n_free_form': 643,
                 'n_mcq': 300,
                 'name': 'private'},
 'score_available': False,
 'submission_csv_path': '/content/CSE151B_Kaggle/results/baseline1_weakest/submission.csv',
 'summary': {'free_form_acc': None,
             'mcq_acc': None,
             'n_correct': 0,
             'n_free_form': 0,
             'n_mcq': 0,
             'n_scored': 0,
             'overall_acc': None},
 'timings': {'generation_sec': 339.3967333410001,
             'prompt_build_sec': 0.07438255999932153,
             'scoring_sec': 0.0008840780001264648}}
"""

In [ ]:
submission_path = BASELINE1_DIR / "submission.csv"

if submission_path.exists():
    sub_df = pd.read_csv(submission_path)
    print(sub_df.shape)
    display(sub_df.head())
    print("Columns:", list(sub_df.columns))
else:
    print("No submission file yet. Run the private test cell first.")

(943, 2)

   id                                           response
0   0  Okay, let's tackle part a) first. The problem ...
1   1  Okay, let's try to figure out this problem. So...
2   2  Okay, let's tackle this problem step by step. ...
3   3  Okay, let's try to figure out this problem ste...
4   4  Okay, let's see. The problem says that the poi...

Columns: ['id', 'response']

# Baseline 2: Output hardening

In [17]:
from baseline.baseline2_runner import run_baseline2_problem_set
from baseline.generation import GenerationConfig

BASELINE2_DIR = RESULTS_DIR / "baseline2_prompt_format"
BASELINE2_DIR.mkdir(parents=True, exist_ok=True)

baseline2_generation_config = GenerationConfig(
    max_new_tokens=4096,
    temperature=0.6,
    top_p=0.95,
    top_k=20,
    min_p=0.0,
    repetition_penalty=1.0,
    presence_penalty=0.0,
    do_sample=True,
)

baseline2_retry_generation_config = GenerationConfig(
    max_new_tokens=1024,
    temperature=0.0,
    top_p=1.0,
    top_k=-1,
    min_p=0.0,
    repetition_penalty=1.0,
    presence_penalty=0.0,
    do_sample=False,
)

In [18]:
print("Model backend:", model_bundle.backend)
print("Model max_model_len:", model_bundle.config.max_model_len)
print("Generation max_new_tokens:", baseline2_generation_config.max_new_tokens)
print("Retry max_new_tokens:", baseline2_retry_generation_config.max_new_tokens)

from baseline.prompt_sets import build_prompt_texts
from prompting.prompt_chain import build_prompt_chain

prompt_chain = build_prompt_chain(strategy_name="baseline2")
prompt_rows = build_prompt_texts(val_set.head(5), model_bundle.tokenizer, prompt_chain=prompt_chain)

for row in prompt_rows:
    toks = model_bundle.tokenizer.encode(row["prompt_text"])
    print(row["id"], "prompt_tokens:", len(toks))

for row in prompt_rows:
  prompt_tokens = len(model_bundle.tokenizer.encode(row["prompt_text"]))
  available = model_bundle.config.max_model_len - prompt_tokens
  effective_new_token_cap = min(baseline2_generation_config.max_new_tokens, available)

  print({
      "id": row["id"],
      "prompt_tokens": prompt_tokens,
      "max_model_len": model_bundle.config.max_model_len,
      "configured_max_new_tokens": baseline2_generation_config.max_new_tokens,
      "effective_new_token_cap": effective_new_token_cap,
  })

Model backend: vllm
Model max_model_len: 32768
Generation max_new_tokens: 4096
Retry max_new_tokens: 1024
990 prompt_tokens: 415
902 prompt_tokens: 288
159 prompt_tokens: 282
431 prompt_tokens: 348
1078 prompt_tokens: 259
{'id': 990, 'prompt_tokens': 415, 'max_model_len': 32768, 'configured_max_new_tokens': 4096, 'effective_new_token_cap': 4096}
{'id': 902, 'prompt_tokens': 288, 'max_model_len': 32768, 'configured_max_new_tokens': 4096, 'effective_new_token_cap': 4096}
{'id': 159, 'prompt_tokens': 282, 'max_model_len': 32768, 'configured_max_new_tokens': 4096, 'effective_new_token_cap': 4096}
{'id': 431, 'prompt_tokens': 348, 'max_model_len': 32768, 'configured_max_new_tokens': 4096, 'effective_new_token_cap': 4096}
{'id': 1078, 'prompt_tokens': 259, 'max_model_len': 32768, 'configured_max_new_tokens': 4096, 'effective_new_token_cap': 4096}

In [19]:
baseline2_train_result = run_baseline2_problem_set(
    problem_set=train_set,
    model_bundle=model_bundle,
    generation_config=baseline2_generation_config,
    retry_generation_config=baseline2_retry_generation_config,
    batch_size=BATCH_SIZE,
    limit=32,
    score=True,
    output_jsonl_path=BASELINE2_DIR / "train_results.jsonl",
    debug_jsonl_path=BASELINE2_DIR / "train_debug.jsonl",
    report_json_path=BASELINE2_DIR / "train_report.json",
    show_progress=True,
)

pprint(baseline2_train_result.report)

Generating:   0%|          | 0/1 [00:00<?, ?it/s]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Generating:   0%|          | 0/1 [00:00<?, ?it/s]

Rendering prompts:   0%|          | 0/8 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/8 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

{'backend': 'vllm',
 'baseline': 'baseline2_prompt_format',
 'batch_size': 32,
 'category_counts': {'uncategorized': 32},
 'category_summary': {'uncategorized': {'accuracy': 0.4375,
                                        'extractable_rate': 0.875,
                                        'formatting_failure_rate': 0.125,
                                        'n': 32,
                                        'n_scored': 32,
                                        'schema_valid_rate': 0.78125}},
 'debug_jsonl_path': '/content/CSE151B_Kaggle/CSE151B_Kaggle/results/baseline2_prompt_format/train_debug.jsonl',
 'formatting': {'extractable_count': 28,
                'extractable_rate': 0.875,
                'formatting_failure_count': 4,
                'formatting_failure_rate': 0.125,
                'initial_extractable_count': 27,
                'initial_extractable_rate': 0.84375,
                'initial_formatting_failure_count': 9,
                'initial_formatting_failure_rate': 0.28125,
                'initial_schema_error_counts': {'missing_boxed_answer_after_final': 5,
                                                'missing_final_answer_marker': 5,
                                                'multi_answer_count_mismatch': 3,
                                                'trailing_text_after_final_box': 4},
                'initial_schema_valid_count': 21,
                'initial_schema_valid_rate': 0.65625,
                'n_outputs': 32,
                'post_sanitize_schema_error_counts': {'missing_boxed_answer_after_final': 5,
                                                      'missing_final_answer_marker': 5,
                                                      'multi_answer_count_mismatch': 3},
                'retry_count': 8,
                'retry_extract_success_count': 1,
                'retry_rate': 0.25,
                'retry_schema_success_count': 1,
                'retry_used_count': 1,
                'retry_used_rate': 0.03125,
                'sanitized_count': 5,
                'sanitized_rate': 0.15625,
                'schema_error_counts': {'missing_boxed_answer_after_final': 4,
                                        'missing_final_answer_marker': 4,
                                        'multi_answer_count_mismatch': 3},
                'schema_valid_count': 25,
                'schema_valid_rate': 0.78125,
                'unextractable_count': 4,
                'unextractable_rate': 0.125},
 'generation': {'backend': 'vllm',
                'batch_size': 32,
                'elapsed_sec': 46.100977733000036,
                'max_new_tokens': 4096,
                'n': 32,
                'responses': ['- For each x in x_list, compute the least odd k '
                              'such that k * 2^x + 1 is prime.\n'
                              '- Check small odd k values starting from 1 for '
                              'each x.\n'
                              '- x=70: k=43 (43*2^70+1 prime)\n'
                              '- x=71: k=37 (37*2^71+1 prime)\n'
                              '- x=72: k=125 (125*2^72+1 prime)\n'
                              '- x=73: k=21 (21*2^73+1 prime)\n'
                              '- x=74: k=70 (70*2^74+1 prime) but 70 is even, '
                              'so k=71? Wait, must be odd, so k=71? Wait no, '
                              'check the choices.\n'
                              '- Wait, better to match with options: Option D '
                              'has [43, 37, 125, 21, 70, 9, 98, 27, 13, 246] '
                              'but 70 is even, so invalid. Option A: '
                              '[44,43,...] 44 even. Option B: [37,35,...] 35 '
                              'odd. Wait, the problem says "least odd number '
                              'k", so k must be odd. So all y_list entries '
                              "must be odd numbers. Check each option's list "
                              'for even numbers.\n'
                              '\n'
                              'Option A: 44 (even), 43 (odd), 129 (odd), 26 '
                              '(even) -> invalid.\n'
                              'Option B: 37 (odd), 35 (odd), 122 (even) -> '
                              'invalid.\n'
                              'Option C: 38 (even) -> invalid.\n'
                              'Option D: 43 (odd), 37 (odd), 125 (odd), 21 '
                              '(odd), 70 (even) -> invalid.\n'
                              'Option E: 39 (odd), 39 (odd), 127 (odd), 23 '
                              '(odd), 67 (odd), 5 (odd), 93 (odd), 29 (odd), '
                              '15 (odd), 249 (odd) -> all odd. Good '
                              'candidate.\n'
                              'Option F: 45 (odd), 44 (even) -> invalid.\n'
                              'Option G: 41 (odd), 42 (even) -> invalid.\n'
                              'Option H: 42 (even) -> invalid.\n'
                              'Option I: 36 (even) -> invalid.\n'
                              'Option J: 40 (even) -> invalid.\n'
                              '\n'
                              'So only option E has all odd numbers. Now '
                              'verify a few with known primes.\n'
                              '\n'
                              'For x=70: k=39 -> 39*2^70 +1. Is this prime? '
                              "Well, the problem states it's defined as the "
                              'least odd k, so if the option says 39, then '
                              "it's correct. Since the other options have even "
                              'numbers which are invalid, E is the answer.\n'
                              '\n'
                              'Final Answer: \\boxed{E}\n'
                              '</think>\n'
                              '\n'
                              'Reasoning:\n'
                              '- All y_list values must be odd (since k is '
                              'odd).\n'
                              '- Options A, B, C, D, F, G, H, I, J contain '
                              'even numbers → invalid.\n'
                              '- Only option E has all odd numbers: [39, 39, '
                              '127, 23, 67, 5, 93, 29, 15, 249].\n'
                              '- Verified as consistent with the definition.\n'
                              '\n'
                              'Final Answer: \\boxed{E}',
                              'A regular $n$-gon has $\\frac{n(n-3)}{2}$ '
                              'diagonals. Set this equal to a nonzero perfect '
                              'square $k^2$, so $\\frac{n(n-3)}{2} = k^2$. '
                              'Rearranging, $n^2 - 3n - 2k^2 = 0$. Solve for '
                              '$n$: $n = \\frac{3 \\pm \\sqrt{9 + 8k^2}}{2}$. '
                              'Since $n > 0$, take the positive root: $n = '
                              '\\frac{3 + \\sqrt{9 + 8k^2}}{2}$. For $n$ to be '
                              'integer, $\\sqrt{9 + 8k^2}$ must be odd '
                              'integer, say $m = \\sqrt{9 + 8k^2}$, so $m^2 - '
                              '8k^2 = 9$. This is a Pell-type equation. The '
                              'fundamental solution for $m^2 - 8k^2 = 9$ is '
                              '$(m,k) = (3,0)$, but $k=0$ gives $n=3/2$, '
                              'invalid. Next solution: $(m,k) = (9,3)$, giving '
                              '$n = (3+9)/2 = 6$. Check: $6$-gon has $6(3)/2 = '
                              '9 = 3^2$, valid. Next solutions: $(m,k) = '
                              '(17,7)$, $n = (3+17)/2 = 10$. Check: $10(7)/2 = '
                              '35$, not square. Wait, miscalculation: $n = (3 '
                              '+ m)/2$, $m=17$ gives $n=10$, diagonals '
                              '$10(10-3)/2=35$, not square. Next: $(m,k) = '
                              '(25,11)$, $n=14$, diagonals $14*11/2=77$, not '
                              'square. Wait, maybe I need to generate '
                              'solutions properly.\n'
                              '\n'
                              'Wait, Pell equation $m^2 - 8k^2 = 9$. The '
                              'fundamental solution for $x^2 - 8y^2 = 1$ is '
                              "$(3,1)$, but here it's $=9$. Let's list small "
                              'solutions:\n'
                              '\n'
                              'k=0: m=3 → n=3/2 invalid\n'
                              'k=1: m^2=9+8=17 not square\n'
                              'k=2: m^2=9+32=41 no\n'
                              'k=3: m^2=9+72=81 → m=9 → n=(3+9)/2=6 → '
                              'diagonals=9=3^2 ✔️\n'
                              'k=4: m^2=9+128=137 no\n'
                              'k=5: m^2=9+200=209 no\n'
                              'k=6: m^2=9+288=297 no\n'
                              'k=7: m^2=9+392=401 no? Wait, 8*49=392, '
                              '9+392=401, not square. Wait earlier I thought '
                              '(17,7) but 17^2=289, 8*7^2=392, 289-392=-103≠9. '
                              'Mistake here.\n'
                              '\n'
                              'Correct: m^2 = 9 + 8k^2. For k=3: 9+8*9=81=9^2, '
                              'yes. Next k: try k=12: 8*144=1152, 1152+9=1161 '
                              'no. k=15: 8*225=1800+9=1809 no. k=21: '
                              '8*441=3528+9=3537 no. Wait maybe better to '
                              'solve the equation.\n'
                              '\n'
                              'm^2 - 8k^2 = 9. This is a hyperbola. Solutions '
                              'can be generated from fundamental solutions '
                              'using the fundamental unit of the ring '
                              'Z[sqrt(8)].\n'
                              '\n'
                              'The equation m^2 - 8k^2 = 9. We have '
                              "(m,k)=(3,0), (9,3) as solutions. Let's see if "
                              '(9,3) can generate more solutions. The '
                              'fundamental solution to x^2 - 8y^2 = 1 is '
                              '(3,1), since 3^2 -8*1^2=1.\n'
                              '\n'
                              'To generate new solutions from (m1,k1), '
                              'multiply by (3 + sqrt(8)):\n'
                              '\n'
                              '(m + k sqrt(8))(3 + sqrt(8)) = (3m + 8k) + (m + '
                              '3k) sqrt(8)\n'
                              '\n'
                              "So new solution (m', k') = (3m + 8k, m + 3k)\n"
                              '\n'
                              'Start with (m,k)=(9,3):\n'
                              '\n'
                              "m' = 3*9 + 8*3 = 27 + 24 = 51\n"
                              '\n'
                              "k' = 9 + 3*3 = 18\n"
                              '\n'
                              'Check: 51^2 -8*18^2 = 2601 - 8*324 = 2601 - '
                              '2592 = 9 ✔️\n'
                              '\n'
                              'n = (3 + 51)/2 = 54/2 = 27\n'
                              '\n'
                              'Diagonals: 27*24/2 = 324 = 18^2 ✔️ (since k=18, '
                              'k^2=324)\n'
                              '\n'
                              'Next solution: apply again to (51,18):\n'
                              '\n'
                              "m'' = 3*51 + 8*18 = 153 + 144 = 297\n"
                              '\n'
                              "k'' = 51 + 3*18 = 51 + 54 = 105\n"
                              '\n'
                              'n = (3 + 297)/2 = 300/2 = 150\n'
                              '\n'
                              'Diagonals: 150*147/2 = 150*73.5? Wait no: '
                              '150*147/2 = 75*147 = 11025. k=105, k^2=11025 '
                              '✔️\n'
                              '\n'
                              "Next: m''' = 3*297 + 8*105 = 891 + 840 = 1731\n"
                              '\n'
                              "k''' = 297 + 3*105 = 297 + 315 = 612\n"
                              '\n'
                              'n = (3 + 1731)/2 = 1734/2 = 867\n'
                              '\n'
                              'Check n=867 < 1000? Yes. Diagonals: 867*864/2 = '
                              "867*432 = let's not compute, but k=612, "
                              "k^2=612^2, so it's a square.\n"
                              '\n'
                              "Next solution: m'''' = 3*1731 + 8*612 = 5193 + "
                              '4896 = 10089\n'
                              '\n'
                              "k'''' = 1731 + 3*612 = 1731 + 1836 = 3567\n"
                              '\n'
                              'n = (3 + 10089)/2 = 10092/2 = 5046 > 1000, too '
                              'big.\n'
                              '\n'
                              "Wait, did we miss any solutions? Let's check if "
                              'there are other fundamental solutions.\n'
                              '\n'
                              'For k=0: (3,0) invalid as n=1.5\n'
                              '\n'
                              'k=3: n=6 (valid)\n'
                              '\n'
                              'Next from (9,3) we got n=27, 150, 867.\n'
                              '\n'
                              "Wait, is there a solution with smaller n? Let's "
                              'check n=3: diagonals=0 (nonzero required, so '
                              'n>=4). n=4: 2 diagonals, not square. n=5: 5 '
                              'diagonals, no. n=6: 9=3^2, yes. n=7: 14, no. '
                              'n=8: 20, no. n=9: 27, no. n=10: 35, no. n=11: '
                              '44, no. n=12: 54, no. n=13: 65, no. n=14: 77, '
                              'no. n=15: 90, no. n=16: 104, no. n=17: 120, no. '
                              'n=18: 135, no. n=19: 152, no. n=20: 170, no. '
                              'n=21: 189, no. n=22: 210, no. n=23: 232, no. '
                              'n=24: 255, no. n=25: 280, no. n=26: 306, no. '
                              'n=27: 27*24/2=324=18^2, yes.\n'
                              '\n'
                              "So n=6,27,150,867. Wait, that's 4 numbers. But "
                              "let's check n=150: 150<1000, yes. n=867<1000, "
                              'yes. Next is 5046>1000.\n'
                              '\n'
                              'Wait, is there another sequence of solutions? '
                              "Let's see if there's a solution with k= "
                              'something else.\n'
                              '\n'
                              'Wait, when we generated solutions, we started '
                              'from (9,3) and applied the recurrence. But '
                              "maybe there's another fundamental solution.\n"
                              '\n'
                              'Check m=3: k=0 invalid.\n'
                              '\n'
                              'm=1: 1-8k^2=9 → -8k^2=8, no.\n'
                              '\n'
                              'm=5: 25-8k^2=9 → 8k^2=16 → k^2=2, no.\n'
                              '\n'
                              'm=7: 49-9=40=8k^2 → k^2=5, no.\n'
                              '\n'
                              'm=9: 81-9=72=8*9 → k=3, yes.\n'
                              '\n'
                              'm=11: 121-9=112=8*14 → k^2=14, no.\n'
                              '\n'
                              'm=13: 169-9=160=8*20 → k^2=20, no.\n'
                              '\n'
                              'm=15: 225-9=216=8*27 → k^2=27, no.\n'
                              '\n'
                              'm=17: 289-9=280=8*35 → k^2=35, no.\n'
                              '\n'
                              'm=19: 361-9=352=8*44 → k^2=44, no.\n'
                              '\n'
                              'm=21: 441-9=432=8*54 → k^2=54, no.\n'
                              '\n'
                              'm=23: 529-9=520=8*65 → k^2=65, no.\n'
                              '\n'
                              'm=25: 625-9=616=8*77 → k^2=77, no.\n'
                              '\n'
                              'm=27: 729-9=720=8*90 → k^2=90, no.\n'
                              '\n'
                              'm=29: 841-9=832=8*104 → k^2=104, no.\n'
                              '\n'
                              'm=31: 961-9=952=8*119 → k^2=119, no.\n'
                              '\n'
                              'm=33: 1089-9=1080=8*135 → k^2=135, no.\n'
                              '\n'
                              'm=35: 1225-9=1216=8*152 → k^2=152, no.\n'
                              '\n'
                              'm=37: 1369-9=1360=8*170 → k^2=170, no.\n'
                              '\n'
                              'm=39: 1521-9=1512=8*189 → k^2=189, no.\n'
                              '\n'
                              'm=41: 1681-9=1672=8*209 → k^2=209, no.\n'
                              '\n'
                              'm=43: 1849-9=1840=8*230 → k^2=230, no.\n'
                              '\n'
                              'm=45: 2025-9=2016=8*252 → k^2=252, no.\n'
                              '\n'
                              'm=47: 2209-9=2200=8*275 → k^2=275, no.\n'
                              '\n'
                              'm=49: 2401-9=2392=8*299 → k^2=299, no.\n'
                              '\n'
                              'm=51: 2601-9=2592=8*324 → k=18, yes, which we '
                              'had.\n'
                              '\n'
                              'So seems like the only solutions are from the '
                              'sequence we generated: n=6,27,150,867.\n'
                              '\n'
                              'Wait, n=6: 6<1000, yes. n=27: yes. n=150: yes. '
                              'n=867: yes. Next is 5046>1000.\n'
                              '\n'
                              'Wait, but the problem says "positive integers n '
                              '< 1000". So 4 numbers. Looking at answer '
                              'choices, J is 4.\n'
                              '\n'
                              'But wait, earlier when I thought n=10 had 35 '
                              'diagonals, which is not square, but maybe I '
                              'missed a solution?\n'
                              '\n'
                              "Wait, let's check n=1: not a polygon. n=2,3: no "
                              'diagonals (n=3 has 0 diagonals). n=4: 2 '
                              'diagonals (not square). n=5: 5 diagonals (no). '
                              'n=6: 9 (yes). n=7: 14 (no). n=8: 20 (no). n=9: '
                              '27 (no). n=10: 35 (no). n=11: 44 (no). n=12: 54 '
                              '(no). n=13: 65 (no). n=14: 77 (no). n=15: 90 '
                              '(no). n=16: 104 (no). n=17: 120 (no). n=18: 135 '
                              '(no). n=19: 152 (no). n=20: 170 (no). n=21: 189 '
                              '(no). n=22: 210 (no). n=23: 232 (no). n=24: 255 '
                              '(no). n=25: 280 (no). n=26: 306 (no). n=27: '
                              '324=18^2 (yes). n=28: 28*25/2=350 (no). n=29: '
                              '29*26/2=377 (no). n=30: 30*27/2=405 (no). ... '
                              'n=150: 150*147/2=11025=105^2 (yes). n=867: '

In [ ]:
"""
'generation_config': {'do_sample': True,
                       'max_new_tokens': 1024,
                       'min_p': 0.0,
                       'presence_penalty': 0.0,
                       'repetition_penalty': 1.0,
                       'temperature': 0.6,
                       'top_k': 20,
                       'top_p': 0.95},
 'output_jsonl_path': '/content/CSE151B_Kaggle/CSE151B_Kaggle/results/baseline2_prompt_format/train_results.jsonl',
 'problem_set': {'n': 32,
                 'n_answered': 32,
                 'n_free_form': 13,
                 'n_mcq': 19,
                 'name': 'public_train_head32'},
 'schema_accuracy': {'retry_used_accuracy': 0.6,
                     'retry_used_n': 5,
                     'schema_invalid_accuracy': 0.08333333333333333,
                     'schema_invalid_n': 24,
                     'schema_valid_accuracy': 0.875,
                     'schema_valid_n': 8},
 'score_available': True,
 'submission_csv_path': None,
 'summary': {'free_form_acc': 0.5384615384615384,
             'mcq_acc': 0.10526315789473684,
             'n_correct': 9,
             'n_free_form': 13,
             'n_mcq': 19,
             'n_scored': 32,
             'overall_acc': 0.28125},
 'timings': {'generation_sec': 11.575837816000103,
             'prompt_build_sec': 0.023429658999930325,
             'retry_generation_sec': 11.110912010999982,
             'scoring_sec': 0.8481839019998461}}
"""

In [ ]:
"""
'generation_config': {'do_sample': True,
                       'max_new_tokens': 4096,
                       'min_p': 0.0,
                       'presence_penalty': 0.0,
                       'repetition_penalty': 1.0,
                       'temperature': 0.6,
                       'top_k': 20,
                       'top_p': 0.95},
 'output_jsonl_path': '/content/CSE151B_Kaggle/CSE151B_Kaggle/results/baseline2_prompt_format/train_results.jsonl',
 'problem_set': {'n': 32,
                 'n_answered': 32,
                 'n_free_form': 13,
                 'n_mcq': 19,
                 'name': 'public_train_head32'},
 'retry_generation_config': {'do_sample': False,
                             'max_new_tokens': 1024,
                             'min_p': 0.0,
                             'presence_penalty': 0.0,
                             'repetition_penalty': 1.0,
                             'temperature': 0.0,
                             'top_k': -1,
                             'top_p': 1.0},
 'schema_accuracy': {'retry_used_accuracy': 0.0,
                     'retry_used_n': 1,
                     'sanitized_accuracy': 0.6,
                     'sanitized_n': 5,
                     'schema_invalid_accuracy': 0.0,
                     'schema_invalid_n': 7,
                     'schema_valid_accuracy': 0.56,
                     'schema_valid_n': 25},
 'score_available': True,
 'submission_csv_path': None,
 'summary': {'free_form_acc': 0.46153846153846156,
             'mcq_acc': 0.42105263157894735,
             'n_correct': 14,
             'n_free_form': 13,
             'n_mcq': 19,
             'n_scored': 32,
             'overall_acc': 0.4375},
 'timings': {'generation_sec': 46.100986020000164,
             'prompt_build_sec': 0.0028652999999394524,
             'retry_generation_sec': 8.265795843999967,
             'scoring_sec': 1.19583538400002}}
"""

In [20]:
baseline2_val_result = run_baseline2_problem_set(
    problem_set=val_set,
    model_bundle=model_bundle,
    generation_config=baseline2_generation_config,
    retry_generation_config=baseline2_retry_generation_config,
    batch_size=BATCH_SIZE,
    limit=None,
    score=True,
    output_jsonl_path=BASELINE2_DIR / "val_results.jsonl",
    debug_jsonl_path=BASELINE2_DIR / "val_debug.jsonl",
    report_json_path=BASELINE2_DIR / "val_report.json",
    show_progress=True,
)

pprint(baseline2_val_result.report)

Generating:   0%|          | 0/8 [00:00<?, ?it/s]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Generating:   0%|          | 0/2 [00:00<?, ?it/s]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Rendering prompts:   0%|          | 0/13 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/13 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Streaming output truncated to the last 5000 lines.
                              'Now, for the model, is it written as '
                              'y=\\frac{2250}{x} or just \\frac{2250}{x}? '
                              'Since it says "y=$ [ANS]", the [ANS] is the '
                              "expression, so I think it's \\frac{2250}{x}.\n"
                              '\n'
                              'But in the box, to be precise.\n'
                              '\n'
                              'I recall that in some contexts, they write the '
                              'whole thing, but the instruction says "the '
                              'final answer must contain only the answer", and '
                              "for the first blank, it's the expression.\n"
                              '\n'
                              "To be safe, I'll write it as per the problem.\n"
                              '\n'
                              'In the reasoning, I have "the model is $ y = '
                              '\\frac{2250}{x} $", so the [ANS] for that is '
                              '\\frac{2250}{x}.\n'
                              '\n'
                              'Similarly, the approximation is 265.\n'
                              '\n'
                              'So, the box should contain \\frac{2250}{x} and '
                              '265, separated by comma.\n'
                              '\n'
                              "But in text, how to represent? Since it's a "
                              'math problem, probably in LaTeX.\n'
                              '\n'
                              'The output is to be in the box with LaTeX.\n'
                              '\n'
                              'In the user\'s message, it says "Final Answer: '
                              '\\boxed{<final answer>}", so I think it\'s '
                              'expected to be LaTeX.\n'
                              '\n'
                              'In the reasoning, I wrote it with LaTeX.\n'
                              '\n'
                              "So, I'll write: "
                              '\\boxed{y=\\dfrac{2250}{x},265}\n'
                              '\n'
                              'The problem says: "the final answer must '
                              'contain only the answer, not explanation." and '
                              '"for multiple [ANS] blanks, put all answers '
                              'inside one box"\n'
                              '\n'
                              'In this case, the first answer is '
                              '"y=\\dfrac{2250}{x}" or just '
                              '"\\dfrac{2250}{x}"?\n'
                              '\n'
                              'Let me see the problem statement: "Your answer '
                              'is $ y=$ [ANS]"\n'
                              '\n'
                              'So, the [ANS] is what comes after y=, so it '
                              'should be the expression, like '
                              '\\dfrac{2250}{x}.\n'
                              '\n'
                              'In the box, if I put "y=\\dfrac{2250}{x},265", '
                              "that might be confusing because it's a string.\n"
                              '\n'
                              'But the instruction says: "Do not write '
                              'anything after the boxed final answer."\n'
                              '\n'
                              "And in the example, it's probably fine.\n"
                              '\n'
                              'To be precise, since the problem says "y=$ '
                              '[ANS]", the answer for [ANS] is the '
                              'expression.\n'
                              '\n'
                              'In the final answer box, it should be the '
                              'values as specified.\n'
                              '\n'
                              "I think it's standard to put the expression for "
                              'the first and the number for the second.\n'
                              '\n'
                              'In the reasoning, I have it as "y = '
                              '\\frac{2250}{x}" and "265".\n'
                              '\n'
                              "For the box, I'll write: "
                              '\\boxed{\\dfrac{2250}{x},265}\n'
                              '\n'
                              'But the problem says "y=$ [ANS]", so the [ANS] '
                              'is the right-hand side, so it should be '
                              '\\dfrac{2250}{x}, not including y=.\n'
                              '\n'
                              'Yes, that makes sense.\n'
                              '\n'
                              'For example, if it were a single answer, it '
                              "might be different, but here it's clear.\n"
                              '\n'
                              'In the output format, it says: "For multiple '
                              '[ANS] blanks, put all answers inside one box '
                              'separated by commas"\n'
                              '\n'
                              'So, the answers are: first blank: '
                              '\\dfrac{2250}{x}, second blank: 265.\n'
                              '\n'
                              'So, the box should contain \\dfrac{2250}{x} and '
                              '265.\n'
                              '\n'
                              'In LaTeX, I can write it as '
                              '\\dfrac{2250}{x},265\n'
                              '\n'
                              'But to make it clear.\n'
                              '\n'
                              'In the box, it should be a single expression.\n'
                              '\n'
                              "I think it's fine.\n"
                              '\n'
                              'In my initial reasoning, I said "y = '
                              '\\frac{2250}{x}", so for the blank, it\'s the '
                              'fraction.\n'
                              '\n'
                              "To confirm, if I were to write the answer, I'd "
                              'say the model is y = 2250/x, so the [ANS] for '
                              'that is 2250/x.\n'
                              '\n'
                              'Similarly, the approximation is 265.\n'
                              '\n'
                              'So, in the box: \\boxed{\\dfrac{2250}{x},265}\n'
                              '\n'
                              'But in text, it might be written without LaTeX, '
                              "but since it's a math problem, probably LaTeX "
                              'is expected.\n'
                              '\n'
                              'The user specified the output format with '
                              "\\boxed{}, so it's for LaTeX.\n"
                              '\n'
                              'In the response, I need to write it as text.\n'
                              '\n'
                              'The user said: "Solve the problem, but keep the '
                              'response short"\n'
                              '\n'
                              'And "the response" is the reasoning and then '
                              'the final answer.\n'
                              '\n'
                              'But the instruction says: "Do not write '
                              'anything after the boxed final answer."\n'
                              '\n'
                              'So, I should only output the reasoning in the '
                              'specified lines, and then the boxed answer.\n'
                              '\n'
                              'The user said: "Reasoning: - ... " and then '
                              '"Final Answer: \\boxed{...}"\n'
                              '\n'
                              'In the reasoning, I have to keep it short.\n'
                              '\n'
                              'In my reasoning, I have:\n'
                              '\n'
                              '- The problem states demand varies inversely as '
                              'price, so $ y = \\frac{k}{x} $.\n'
                              '\n'
                              '- Plug in $ x = 4.5 $, $ y = 500 $ to find $ k '
                              '$: $ 500 = \\frac{k}{4.5} \\implies k = 2250 '
                              '$.\n'
                              '\n'
                              '- Thus, the model is $ y = \\frac{2250}{x} $.\n'
                              '\n'
                              '- For $ x = 8.5 $, $ y = \\frac{2250}{8.5} '
                              '\\approx 264.70588235 $.\n'
                              '\n'
                              '- Rounded to the nearest whole number, $ y '
                              '\\approx 265 $.\n'
                              '\n'
                              "That's five lines, which is less than 8.\n"
                              '\n'
                              'I can make it shorter.\n'
                              '\n'
                              'For example: Demand varies inversely, so $ y = '
                              '\\frac{k}{x} $. With $ x=4.5 $, $ y=500 $, $ '
                              'k=500 \\times 4.5 = 2250 $. Model: $ y = '
                              '\\frac{2250}{x} $. At $ x=8.5 $, $ y \\approx '
                              '265 $.\n'
                              '\n'
                              "That's four lines.\n"
                              '\n'
                              "I think it's fine.\n"
                              '\n'
                              'Now, for the final answer, as per the problem, '
                              'it should be the two answers.\n'
                              '\n'
                              'The problem says: "Your answer is $ y=$ [ANS]" '
                              'so [ANS] is the expression for y.\n'
                              '\n'
                              'And "Approximate the demand... Your answer is: '
                              '[ANS]" so that\'s the number.\n'
                              '\n'
                              'So, in the box: \\dfrac{2250}{x},265\n'
                              '\n'
                              'But to write it in the box.\n'
                              '\n'
                              'In the output, I need to write:\n'
                              '\n'
                              'Reasoning:\n'
                              '- Demand varies inversely, so $ y = '
                              '\\frac{k}{x} $.\n'
                              '- $ k = 500 \\times 4.5 = 2250 $.\n'
                              '- Model: $ y = \\frac{2250}{x} $.\n'
                              '- At $ x = 8.5 $, $ y = \\frac{2250}{8.5} '
                              '\\approx 264.71 $, so $ y \\approx 265 $.\n'
                              '\n'
                              'But the instruction says "do not repeat checks '
                              'unless necessary", and "use at most 8 concise '
                              'lines".\n'
                              '\n'
                              'This is four lines.\n'
                              '\n'
                              'I can shorten: Inverse variation: $ y = '
                              '\\frac{k}{x} $. With $ x=4.5 $, $ y=500 $, $ '
                              'k=2250 $. Model: $ y = \\frac{2250}{x} $. '
                              'Demand at $ x=8.5 $: $ \\frac{2250}{8.5} '
                              '\\approx 265 $.\n'
                              '\n'
                              'Yes.\n'
                              '\n'
                              'Now, for the final answer, I need to output '
                              '\\boxed{\\dfrac{2250}{x},265}\n'
                              '\n'
                              'But in the box, should it be with the y= or '
                              'not?\n'
                              '\n'
                              'I think without, since [ANS] is for the '
                              'expression.\n'
                              '\n'
                              "To be safe, I'll assume it's the expression.\n"
                              '\n'
                              'In the problem, it says "Your answer is $ y=$ '
                              '[ANS]", so the answer they want in the blank is '
                              'the fraction.\n'
                              '\n'
                              "Similarly, for the second, it's the number.\n"
                              '\n'
                              'So, in the box, it should be the fraction and '
                              'the number.\n'
                              '\n'
                              'In LaTeX, \\dfrac{2250}{x} is fine.\n'
                              '\n'
                              "Since it's a single box, and separated by "
                              'comma.\n'
                              '\n'
                              'The instruction says: "For multiple [ANS] '
                              'blanks, put all answers inside one box '
                              'separated by commas"\n'
                              '\n'
                              'So, yes.\n'
                              '\n'
                              "I think that's it.\n"
                              '\n'
                              'So, my response will be:\n'
                              '\n'
                              'Reasoning:\n'
                              '- Demand varies inversely, so $ y = '
                              '\\frac{k}{x} $.\n'
                              '- $ k = 500 \\times 4.5 = 2250 $.\n'
                              '- Model: $ y = \\frac{2250}{x} $.\n'
                              '- At $ x = 8.5 $, $ y \\approx 265 $.\n'
                              '\n'
                              'Final Answer: \\boxed{\\dfrac{2250}{x},265}\n'
                              '\n'
                              'In the last line, I said "y ≈ 265" but the '
                              "approximation is for the demand, and it's "
                              'rounded, so 265 is fine.\n'
                              '\n'
                              'The problem says "approximate", and I have it '
                              'as 265, which is integer.\n'
                              '\n'
                              'In the reasoning, I have it as "y ≈ 265", but '
                              "in the box, it's just the number.\n"
                              '\n'
                              "In the box, it's the answers: first is "
                              '\\dfrac{2250}{x}, second is 265.\n'
                              '\n'
                              'So, no "y=".\n'
                              '\n'
                              'Yes.\n'
                              '\n'
                              "I think that's correct.\n"
                              '\n'
                              'To make it shorter: the reasoning can be one '
                              'line per point.\n'
                              '\n'
                              'But I have four lines, which is fine.\n'
                              '\n'
                              'The instruction says "use at most 8 concise '
                              'lines", so it\'s ok.\n'
                              '\n'
                              'Now, for the box, in the response, I need to '
                              'write it exactly.\n'
                              '\n'
                              'Since the user might expect plain text, but '
                              'given the context, LaTeX is fine.\n'
                              '\n'
                              'In the output, it should be rendered.\n'
                              '\n'
                              "But for the purpose, I'll write it as "
                              'specified.\n'
                              '\n'
                              'So, final answer box: '
                              '\\boxed{\\dfrac{2250}{x},265}\n'
                              '\n'
                              'In some formats, they might write it without '
                              'LaTeX, but since the user used \\boxed{}, I '
                              'think LaTeX is intended.\n'
                              '\n'
                              'To be safe, I can write it as text, but I think '
                              'for this platform, LaTeX is ok.\n'
                              '\n'
                              'The user said: "Follow the required output '
                              'format exactly."\n'
                              '\n'
                              'And in the example, they have \\boxed{...}, so '
                              "I'll use LaTeX.\n"
                              '\n'
                              "So, I'll go with that.\n"
                              '</think>\n'
                              '\n'
                              'Reasoning:\n'
                              '- Demand varies inversely, so $ y = '
                              '\\frac{k}{x} $.\n'
                              '- $ k = 500 \\times 4.5 = 2250 $.\n'
                              '- Model: $ y = \\frac{2250}{x} $.\n'
                              '- At $ x = 8.5 $, $ y \\approx 265 $.\n'
                              '\n'
                              'Final Answer: \\boxed{\\dfrac{2250}{x},265}',
                              '- First sequence: each term is multiplied by 2, '
                              'so exponential.\n'
                              '- Second sequence: each term decreases by 2, so '
                              'linear.\n'
                              '- Third sequence: each term increases by 2, so '
                              'linear.\n'
                              '- Fourth sequence: differences are 1, 2, 3, 4, '
                              'so quadratic, neither.\n'
                              '- Fifth sequence: each term multiplied by 4, so '
                              'exponential.\n'
                              '- Sixth sequence: terms are $1^5, 2^4, 3^3, '
                              '4^2, 5^1$, so neither.\n'
                              '\n'
                              'Final Answer: \\boxed{Exponential, Linear, '
                              'Linear, Neither, Exponential, Neither}\n'
                              '�\n'
                              '<think>\n'
                              "Okay, let's tackle this problem step by step. "
                              'So, we have six sequences here, and we need to '
                              'classify each as linear, exponential, or '
                              'neither. Let me go through each one.\n'
                              '\n'
                              'First sequence: 1, 2, 4, 8, 16,... Hmm, each '
                              "term is doubling. So 1*2=2, 2*2=4, etc. That's "
                              'a geometric sequence, which is exponential. So '
                              'first answer should be Exponential.\n'
                              '\n'
                              'Second sequence: -6, -8, -10, -12, -14,... '

In [ ]:
"""
'generation_config': {'do_sample': True,
                       'max_new_tokens': 1024,
                       'min_p': 0.0,
                       'presence_penalty': 0.0,
                       'repetition_penalty': 1.0,
                       'temperature': 0.6,
                       'top_k': 20,
                       'top_p': 0.95},
 'output_jsonl_path': '/content/CSE151B_Kaggle/CSE151B_Kaggle/results/baseline2_prompt_format/val_results.jsonl',
 'problem_set': {'n': 225,
                 'n_answered': 225,
                 'n_free_form': 150,
                 'n_mcq': 75,
                 'name': 'public_val'},
 'schema_accuracy': {'retry_used_accuracy': 0.6590909090909091,
                     'retry_used_n': 44,
                     'schema_invalid_accuracy': 0.17333333333333334,
                     'schema_invalid_n': 150,
                     'schema_valid_accuracy': 0.76,
                     'schema_valid_n': 75},
 'score_available': True,
 'submission_csv_path': None,
 'summary': {'free_form_acc': 0.4666666666666667,
             'mcq_acc': 0.17333333333333334,
             'n_correct': 83,
             'n_free_form': 150,
             'n_mcq': 75,
             'n_scored': 225,
             'overall_acc': 0.3688888888888889},
 'timings': {'generation_sec': 82.84365255199987,
             'prompt_build_sec': 0.02054123199991409,
             'retry_generation_sec': 69.44308633399987,
             'scoring_sec': 14.325112181999884}}
"""

In [ ]:
"""
'generation_config': {'do_sample': True,
                       'max_new_tokens': 4096,
                       'min_p': 0.0,
                       'presence_penalty': 0.0,
                       'repetition_penalty': 1.0,
                       'temperature': 0.6,
                       'top_k': 20,
                       'top_p': 0.95},
 'output_jsonl_path': '/content/CSE151B_Kaggle/CSE151B_Kaggle/results/baseline2_prompt_format/val_results.jsonl',
 'problem_set': {'n': 225,
                 'n_answered': 225,
                 'n_free_form': 150,
                 'n_mcq': 75,
                 'name': 'public_val'},
 'retry_generation_config': {'do_sample': False,
                             'max_new_tokens': 1024,
                             'min_p': 0.0,
                             'presence_penalty': 0.0,
                             'repetition_penalty': 1.0,
                             'temperature': 0.0,
                             'top_k': -1,
                             'top_p': 1.0},
 'schema_accuracy': {'retry_used_accuracy': 0.25,
                     'retry_used_n': 8,
                     'sanitized_accuracy': 0.3142857142857143,
                     'sanitized_n': 35,
                     'schema_invalid_accuracy': 0.05405405405405406,
                     'schema_invalid_n': 37,
                     'schema_valid_accuracy': 0.6063829787234043,
                     'schema_valid_n': 188},
 'score_available': True,
 'submission_csv_path': None,
 'summary': {'free_form_acc': 0.56,
             'mcq_acc': 0.4266666666666667,
             'n_correct': 116,
             'n_free_form': 150,
             'n_mcq': 75,
             'n_scored': 225,
             'overall_acc': 0.5155555555555555},
 'timings': {'generation_sec': 341.6052394200001,
             'prompt_build_sec': 0.023227069000085976,
             'retry_generation_sec': 21.939288180000176,
             'scoring_sec': 19.803487271999984}}
"""

In [ ]:
baseline2_private_result = run_baseline2_problem_set(
    problem_set=private_set,
    model_bundle=model_bundle,
    generation_config=baseline2_generation_config,
    retry_generation_config=baseline2_retry_generation_config,
    batch_size=BATCH_SIZE,
    limit=None,
    score=False,
    output_jsonl_path=BASELINE2_DIR / "private_results.jsonl",
    debug_jsonl_path=BASELINE2_DIR / "private_debug.jsonl",
    submission_csv_path=BASELINE2_DIR / "submission.csv",
    report_json_path=BASELINE2_DIR / "private_report.json",
    show_progress=True,
)

pprint(baseline2_private_result.report)

In [ ]:
"""
'generation_config': {'do_sample': True,
                       'max_new_tokens': 1024,
                       'min_p': 0.0,
                       'presence_penalty': 0.0,
                       'repetition_penalty': 1.0,
                       'temperature': 0.6,
                       'top_k': 20,
                       'top_p': 0.95},
 'output_jsonl_path': '/content/CSE151B_Kaggle/CSE151B_Kaggle/results/baseline2_prompt_format/private_results.jsonl',
 'problem_set': {'n': 943,
                 'n_answered': 0,
                 'n_free_form': 643,
                 'n_mcq': 300,
                 'name': 'private'},
 'schema_accuracy': {'retry_used_accuracy': None,
                     'retry_used_n': 0,
                     'schema_invalid_accuracy': None,
                     'schema_invalid_n': 0,
                     'schema_valid_accuracy': None,
                     'schema_valid_n': 0},
 'score_available': False,
 'submission_csv_path': '/content/CSE151B_Kaggle/CSE151B_Kaggle/results/baseline2_prompt_format/submission.csv',
 'summary': {'free_form_acc': None,
             'mcq_acc': None,
             'n_correct': 0,
             'n_free_form': 0,
             'n_mcq': 0,
             'n_scored': 0,
             'overall_acc': None},
 'timings': {'generation_sec': 334.20872846600014,
             'prompt_build_sec': 0.07997702800003026,
             'retry_generation_sec': 279.99592230300004,
             'scoring_sec': 0.004742979999718955}}
"""

In [ ]:
"""
'generation_config': {'do_sample': True,
                       'max_new_tokens': 4096,
                       'min_p': 0.0,
                       'presence_penalty': 0.0,
                       'repetition_penalty': 1.0,
                       'temperature': 0.6,
                       'top_k': 20,
                       'top_p': 0.95},
 'output_jsonl_path': '/content/CSE151B_Kaggle/CSE151B_Kaggle/results/baseline2_prompt_format/private_results.jsonl',
 'problem_set': {'n': 943,
                 'n_answered': 0,
                 'n_free_form': 643,
                 'n_mcq': 300,
                 'name': 'private'},
 'retry_generation_config': {'do_sample': False,
                             'max_new_tokens': 1024,
                             'min_p': 0.0,
                             'presence_penalty': 0.0,
                             'repetition_penalty': 1.0,
                             'temperature': 0.0,
                             'top_k': -1,
                             'top_p': 1.0},
 'schema_accuracy': {'retry_used_accuracy': None,
                     'retry_used_n': 0,
                     'sanitized_accuracy': None,
                     'sanitized_n': 0,
                     'schema_invalid_accuracy': None,
                     'schema_invalid_n': 0,
                     'schema_valid_accuracy': None,
                     'schema_valid_n': 0},
 'score_available': False,
 'submission_csv_path': '/content/CSE151B_Kaggle/CSE151B_Kaggle/results/baseline2_prompt_format/submission.csv',
 'summary': {'free_form_acc': None,
             'mcq_acc': None,
             'n_correct': 0,
             'n_free_form': 0,
             'n_mcq': 0,
             'n_scored': 0,
             'overall_acc': None},
 'timings': {'generation_sec': 1360.692972251,
             'prompt_build_sec': 0.08002269100006743,
             'retry_generation_sec': 79.66110282999989,
             'scoring_sec': 0.008488914999816188}}
"""

In [22]:
pd.DataFrame([
    baseline2_val_result.report["formatting"]
]).T.rename(columns={0: "value"})

                                                                               value
n_outputs                                                                        225
initial_schema_valid_count                                                       158
initial_schema_valid_rate                                                   0.702222
schema_valid_count                                                               188
schema_valid_rate                                                           0.835556
initial_formatting_failure_count                                                  60
initial_formatting_failure_rate                                             0.266667
formatting_failure_count                                                          27
formatting_failure_rate                                                         0.12
initial_extractable_count                                                        191
initial_extractable_rate                                                    0.848889
extractable_count                                                                198
extractable_rate                                                                0.88
unextractable_count                                                               27
unextractable_rate                                                              0.12
sanitized_count                                                                   35
sanitized_rate                                                              0.155556
retry_count                                                                       45
retry_rate                                                                       0.2
retry_used_count                                                                   8
retry_used_rate                                                             0.035556
retry_schema_success_count                                                         8
retry_extract_success_count                                                        7
initial_schema_error_counts        {'missing_boxed_answer_after_final': 35, 'miss...
post_sanitize_schema_error_counts  {'missing_boxed_answer_after_final': 34, 'miss...
schema_error_counts                {'missing_boxed_answer_after_final': 27, 'miss...

In [23]:
baseline2_val_result.report["formatting"]["schema_error_counts"]

{'missing_boxed_answer_after_final': 27,
 'missing_final_answer_marker': 27,
 'multi_answer_count_mismatch': 10}

In [24]:
bad_schema_rows = [
    row for row in baseline2_val_result.scored_rows
    if not row.get("schema_valid")
]

len(bad_schema_rows), bad_schema_rows[:3]

(37,
 [{'id': 251,
   'is_mcq': True,
   'gold': 'J',
   'response': 'Reasoning:\n- Start with the law of cosines: $a^2 + c^2 - b^2 = 2ac \\cos B$.\n- Given $b^2 \\cos^2 B = a^2 + c^2$, so $b^2 \\cos^2 B - (a^2 + c^2) = 0$.\n- Substitute $a^2 + c^2 = b^2 - 2ac \\cos B$ into the equation: $b^2 \\cos^2 B - (b^2 - 2ac \\cos B) = 0$.\n- Simplify: $b^2 (\\cos^2 B - 1) + 2ac \\cos B = 0$.\n- Use $\\cos^2 B - 1 = -\\sin^2 B$: $-b^2 \\sin^2 B + 2ac \\cos B = 0$.\n- Rearrange: $2ac \\cos B = b^2 \\sin^2 B$.\n- From law of sines, $b = 2R \\sin B$, $a = 2R \\sin A$, $c = 2R \\sin C$, so $ac = 4R^2 \\sin A \\sin C$.\n- Substitute: $2(4R^2 \\sin A \\sin C) \\cos B = (4R^2 \\sin^2 B) \\sin^2 B$.\n- Simplify: $8R^2 \\sin A \\sin C \\cos B = 4R^2 \\sin^4 B$.\n- Divide both sides by $4R^2$: $2 \\sin A \\sin C \\cos B = \\sin^4 B$.\n- Use product-to-sum: $2 \\sin A \\sin C = \\cos(A - C) - \\cos(A + C)$.\n- Since $A + C = \\pi - B$, $\\cos(A + C) = -\\cos B$, so: $2 \\sin A \\sin C = \\cos(A - C) + \\cos B$.\n- Substitute back: $(\\cos(A - C) + \\cos B) \\cos B = \\sin^4 B$.\n- Expand: $\\cos(A - C) \\cos B + \\cos^2 B = \\sin^4 B$.\n- Use $\\sin^2 B = 1 - \\cos^2 B$, so $\\sin^4 B = (1 - \\cos^2 B)^2 = 1 - 2\\cos^2 B + \\cos^4 B$.\n- Rearrange: $\\cos(A - C) \\cos B = 1 - 2\\cos^2 B + \\cos^4 B - \\cos^2 B = 1 - 3\\cos^2 B + \\cos^4 B$.\n- This seems messy. Alternative approach: From $b^2 \\cos^2 B = a^2 + c^2$ and law of cosines $b^2 = a^2 + c^2 - 2ac \\cos B$, substitute $a^2 + c^2 = b^2 \\cos^2 B$ into this: $b^2 = b^2 \\cos^2 B - 2ac \\cos B$.\n- Then $b^2 (1 - \\cos^2 B) = -2ac \\cos B$.\n- Since $1 - \\cos^2 B = \\sin^2 B$, $b^2 \\sin^2 B = -2ac \\cos B$.\n- Left side is positive, so right side must be positive: $-2ac \\cos B > 0$. Since $a, c > 0$, $\\cos B < 0$, so $B$ is obtuse. Wait, but the options include J. obtuse, but let\'s check the sign again.\n\nWait, from $b^2 = a^2 + c^2 - 2ac \\cos B$ and given $b^2 \\cos^2 B = a^2 + c^2$, so substitute $a^2 + c^2 = b^2 \\cos^2 B$ into law of cosines: $b^2 = b^2 \\cos^2 B - 2ac \\cos B$.\n\nThen $b^2 - b^2 \\cos^2 B = -2ac \\cos B$ => $b^2 \\sin^2 B = -2ac \\cos B$.\n\nLeft side: $b^2 \\sin^2 B > 0$ (since $b > 0$, $\\sin B > 0$ for $0 < B < \\pi$).\n\nRight side: $-2ac \\cos B$. Since $a, c > 0$, $-2ac < 0$, so for the right side to be positive, $\\cos B < 0$. Therefore, $B$ is obtuse. So answer is J.\n\nBut let\'s see the options: J is "obtuse". The problem says "then B is", and options include J. obtuse.\n\nWait, but let\'s check if B can be obtuse. Suppose B is obtuse, then cos B < 0. Given equation: $b^2 \\cos^2 B = a^2 + c^2$. Since cos^2 B is positive, left side is positive, which is good. But from the derivation, we have $b^2 \\sin^2 B = -2ac \\cos B > 0$, which holds because cos B < 0.\n\nWait, but let\'s test with a specific angle. Suppose B = 2π/3 (obtuse). Then cos B = -1/2, cos^2 B = 1/4.\n\nLaw of cosines: b^2 = a^2 + c^2 - 2ac*(-1/2) = a^2 + c^2 + ac.\n\nGiven equation: b^2*(1/4) = a^2 + c^2 => b^2 = 4(a^2 + c^2).\n\nSo 4(a^2 + c^2) = a^2 + c^2 + ac => 3(a^2 + c^2) = ac.\n\nBut 3(a^2 + c^2) >= 3*2ac = 6ac > ac (since ac > 0), so no solution for B=2π/3.\n\nWait, that\'s a problem. So my earlier conclusion that B is obtuse is wrong because the equation 3(a^2 + c^2) = ac has no solution (left side >= 6ac > ac).\n\nSo where did I go wrong?\n\nLet\'s start over.\n\nGiven: $b^2 \\cos^2 B = a^2 + c^2$ (1)\n\nLaw of cosines: $b^2 = a^2 + c^2 - 2ac \\cos B$ (2)\n\nFrom (1), $a^2 + c^2 = b^2 \\cos^2 B$. Plug into (2):\n\n$b^2 = b^2 \\cos^2 B - 2ac \\cos B$\n\nRearrange: $b^2 (1 - \\cos^2 B) = -2ac \\cos B$\n\n$b^2 \\sin^2 B = -2ac \\cos B$ (3)\n\nNow, left side: $b^2 \\sin^2 B > 0$ (since b > 0, 0 < B < π, so sin B > 0)\n\nRight side: $-2ac \\cos B$. Since a, c > 0, -2ac < 0. Therefore, for right side to be positive, cos B < 0. So B is obtuse.\n\nBut when I tested B=2π/3, it didn\'t work. Why?\n\nBecause for B obtuse, cos B < 0, but the equation (3) must hold. Let\'s take B such that cos B = -k, k > 0.\n\nThen (3): $b^2 \\sin^2 B = 2ac k$.\n\nFrom law of sines: a = 2R sin A, c = 2R sin C, b = 2R sin B.\n\nSo (3): (4R^2 sin^2 B) = 2*(4R^2 sin A sin C)*k => sin^2 B = 2 sin A sin C k.\n\nBut k = -cos B, so sin^2 B = -2 sin A sin C cos B.\n\nAlso, A + C = π - B, so C = π - B - A.\n\nLet\'s assume B is fixed, say B = 2π/3, then A + C = π/3.\n\nsin^2(2π/3) = (3/4) = -2 sin A sin C cos(2π/3) = -2 sin A sin C*(-1/2) = sin A sin C.\n\nSo 3/4 = sin A sin C.\n\nBut A + C = π/3, so sin A sin C = [cos(A - C) - cos(A + C)]/2 = [cos(A - C) - cos(π/3)]/2 = [cos(A - C) - 1/2]/2.\n\nSo 3/4 = [cos(A - C) - 1/2]/2 => 3/2 = cos(A - C) - 1/2 => cos(A - C) = 2.\n\nBut cos(A - C) <= 1, so impossible. Hence, no solution for B=2π/3.\n\nSo my initial conclusion that B is obtuse is incorrect because the equation has no solution for obtuse B? Wait, but the problem states "if b^2 cos^2 B = a^2 + c^2", so we need to find B such that this equation holds for some triangle.\n\nSo let\'s solve for B.\n\nFrom (3): $b^2 \\sin^2 B = -2ac \\cos B$.\n\nFrom law of sines, $a = 2R \\sin A$, $c = 2R \\sin C$, so $ac = 4R^2 \\sin A \\sin C$.\n\nAlso, $b = 2R \\sin B$, so $b^2 = 4R^2 \\sin^2 B$.\n\nPlug into (3): $4R^2 \\sin^2 B \\cdot \\sin^2 B = -2 \\cdot 4R^2 \\sin A \\sin C \\cdot \\cos B$.\n\nSimplify: $4R^2 \\sin^4 B = -8R^2 \\sin A \\sin C \\cos B$.\n\nDivide both sides by 4R^2: $\\sin^4 B = -2 \\sin A \\sin C \\cos B$.\n\nSince A + C = π - B, $\\sin A \\sin C = [\\cos(A - C) - \\cos(A + C)]/2 = [\\cos(A - C) + \\cos B]/2$.\n\nSo: $\\sin^4 B = -2 \\cdot [\\cos(A - C) + \\cos B]/2 \\cdot \\cos B = -[\\cos(A - C) + \\cos B] \\cos B$.\n\nThus: $\\sin^4 B = -\\cos(A - C) \\cos B - \\cos^2 B$.\n\nRearrange: $\\cos(A - C) \\cos B = -\\sin^4 B - \\cos^2 B$.\n\nLeft side: $\\cos(A - C) \\cos B$. Since $|A - C| < \\pi$ (as A and C are angles in a triangle), $\\cos(A - C) \\leq 1$ and $\\cos B$ is a real number.\n\nRight side: $-\\sin^4 B - \\cos^2 B = - (1 - \\cos^2 B)^2 - \\cos^2 B = - (1 - 2\\cos^2 B + \\cos^4 B) - \\cos^2 B = -1 + 2\\cos^2 B - \\cos^4 B - \\cos^2 B = -1 + \\cos^2 B - \\cos^4 B$.\n\nLet $x = \\cos^2 B$, so right side = $-1 + x - x^2$.\n\nLeft side: $\\cos(A - C) \\cos B$. Since $|\\cos(A - C)| \\leq 1$, and $\\cos B$ is real, the maximum of left side is $| \\cos B |$ (when $\\cos(A - C) = \\pm 1$).\n\nSo we have $| \\cos B | \\geq -1 + \\cos^2 B - \\cos^4 B$.\n\nLet $f(x) = -1 + x - x^2$ for $x = \\cos^2 B \\in (0,1]$ (since B is an angle in a triangle, 0 < B < π, so x ∈ (0,1]).\n\nWe need $| \\cos B | \\geq f(x)$. Since $x = \\cos^2 B$, $| \\cos B | = \\sqrt{x}$.\n\nSo inequality: $\\sqrt{x} \\geq -1 + x - x^2$.\n\nLet $g(x) = -1 + x - x^2 - \\sqrt{x}$. We need $g(x) \\leq 0$.\n\nTest x=1: g(1) = -1 + 1 - 1 - 1 = -2 ≤ 0.\n\nx=1/2: g(1/2) = -1 + 1/2 - 1/4 - √(1/2) = -0.75 - 0.707 ≈ -1.457 ≤ 0.\n\nx=0.25: g(0.25) = -1 + 0.25 - 0.0625 - 0.5 = -1.3125 ≤ 0.\n\nx approaching 0: g(x) ≈ -1 + 0 - 0 - 0 = -1 ≤ 0.\n\nSo the inequality holds for all x ∈ (0,1]. But we need to find B such that the original equation holds.\n\nWait, maybe another approach: use the given equation and law of cosines to express in terms of B.\n\nFrom (1): $a^2 + c^2 = b^2 \\cos^2 B$.\n\nFrom law of cosines: $b^2 = a^2 + c^2 - 2ac \\cos B = b^2 \\cos^2 B - 2ac \\cos B$.\n\nSo $b^2 (1 - \\cos^2 B) = -2ac \\cos B$ => $b^2 \\sin^2 B = -2ac \\cos B$.\n\nNow, by the AM ≥ GM inequality, $a^2 + c^2 \\geq 2ac$, so from (1), $b^2 \\cos^2 B \\geq 2ac$.\n\nFrom the previous equation, $ac = - (b^2 \\sin^2 B)/(2 \\cos B)$.\n\nSubstitute into AM ≥ GM: $b^2 \\cos^2 B \\geq 2 \\cdot (b^2 \\sin^2 B)/(2 \\cos B) = b^2 \\sin^2 B / \\cos B$.\n\nAssuming $b^2 > 0$, divide both sides by $b^2$: $\\cos^2 B \\geq \\sin^2 B / \\cos B$.\n\nMultiply both sides by $\\cos B$ (we need to consider the sign of cos B):\n\nCase 1: cos B > 0 (B acute). Then inequality becomes $\\cos^3 B \\geq \\sin^2 B = 1 - \\cos^2 B$.\n\nSo $\\cos^3 B + \\cos^2 B - 1 \\geq 0$.\n\nLet h(θ) = cos^3 θ + cos^2 θ - 1 for θ ∈ (0, π/2).\n\nh(0) = 0 + 1 - 1 = 0.\n\nh(π/2) = 0 + 0 - 1 = -1.\n\nh\'(θ) = -3 cos^2 θ sin θ - 2 cos θ sin θ = -sin θ cos θ (3 cos θ + 2) < 0 for θ ∈ (0, π/2).\n\nSo h(θ) is decreasing from 0 to -1, so h(θ) < 0 for θ ∈ (0, π/2). Thus, no solution for B acute.\n\nCase 2: cos B < 0 (B obtuse). Then multiplying by cos B reverses inequality: $\\cos^3 B \\leq \\sin^2 B = 1 - \\cos^2 B$.\n\nSo $\\cos^3 B + \\cos^2 B - 1 \\leq 0$.\n\nLet θ = B, obtuse, so θ ∈ (π/2, π), cos θ ∈ (-1, 0).\n\nLet x = cos θ, x ∈ (-1, 0).\n\nInequality: x^3 + x^2 - 1 ≤ 0.\n\nAt x = -1: (-1)^3 + (-1)^2 - 1 = -1 + 1 - 1 = -1 ≤ 0.\n\nAt x = 0: 0 + 0 - 1 = -1 ≤ 0.\n\nDerivative: 3x^2 + 2x = x(3x + 2). Critical points at x=0 (not in (-1,0)) and x=-2/3.\n\nAt x=-2/3: (-8/27) + (4/9) - 1 = (-8/27 + 12/27) - 1 = 4/27 - 1 = -23/27 ≤ 0.\n\nSo x^3 + x^2 - 1 ≤ 0 for all x ∈ (-1, 0). So the inequality holds for all obtuse B?\n\nBut earlier test with B=2π/3 didn\'t work. What\'s the issue?\n\nWait, in the AM ≥ GM step, we have $a^2 + c^2 \\geq 2ac$, so $b^2 \\cos^2 B \\geq 2ac$. But from the equation, $ac = - (b^2 \\sin^2 B)/(2 \\cos B)$. Since B is obtuse, cos B < 0, so -cos B > 0, so ac > 0, which is good.\n\nLet\'s take B = π/2 (right angle). Then cos B = 0, but given equation: b^2 * 0 = a^2',
   'correct': False,
   'category': None,
   'route_name': 'mcq',
   'template_name': 'baseline2_mcq',
   'prompt_metadata': {'answer_format': 'mcq',
    'strategy_name': 'baseline2',
    'route_name': 'mcq',
    'tags': []},
   'raw_output': 'Reasoning:\n- Start with the law of cosines: $a^2 + c^2 - b^2 = 2ac \\cos B$.\n- Given $b^2 \\cos^2 B = a^2 + c^2$, so $b^2 \\cos^2 B - (a^2 + c^2) = 0$.\n- Substitute $a^2 + c^2 = b^2 - 2ac \\cos B$ into the equation: $b^2 \\cos^2 B - (b^2 - 2ac \\cos B) = 0$.\n- Simplify: $b^2 (\\cos^2 B - 1) + 2ac \\cos B = 0$.\n- Use $\\cos^2 B - 1 = -\\sin^2 B$: $-b^2 \\sin^2 B + 2ac \\cos B = 0$.\n- Rearrange: $2ac \\cos B = b^2 \\sin^2 B$.\n- From law of sines, $b = 2R \\sin B$, $a = 2R \\sin A$, $c = 2R \\sin C$, so $ac = 4R^2 \\sin A \\sin C$.\n- Substitute: $2(4R^2 \\sin A \\sin C) \\cos B = (4R^2 \\sin^2 B) \\sin^2 B$.\n- Simplify: $8R^2 \\sin A \\sin C \\cos B = 4R^2 \\sin^4 B$.\n- Divide both sides by $4R^2$: $2 \\sin A \\sin C \\cos B = \\sin^4 B$.\n- Use product-to-sum: $2 \\sin A \\sin C = \\cos(A - C) - \\cos(A + C)$.\n- Since $A + C = \\pi - B$, $\\cos(A + C) = -\\cos B$, so: $2 \\sin A \\sin C = \\cos(A - C) + \\cos B$.\n- Substitute back: $(\\cos(A - C) + \\cos B) \\cos B = \\sin^4 B$.\n- Expand: $\\cos(A - C) \\cos B + \\cos^2 B = \\sin^4 B$.\n- Use $\\sin^2 B = 1 - \\cos^2 B$, so $\\sin^4 B = (1 - \\cos^2 B)^2 = 1 - 2\\cos^2 B + \\cos^4 B$.\n- Rearrange: $\\cos(A - C) \\cos B = 1 - 2\\cos^2 B + \\cos^4 B - \\cos^2 B = 1 - 3\\cos^2 B + \\cos^4 B$.\n- This seems messy. Alternative approach: From $b^2 \\cos^2 B = a^2 + c^2$ and law of cosines $b^2 = a^2 + c^2 - 2ac \\cos B$, substitute $a^2 + c^2 = b^2 \\cos^2 B$ into this: $b^2 = b^2 \\cos^2 B - 2ac \\cos B$.\n- Then $b^2 (1 - \\cos^2 B) = -2ac \\cos B$.\n- Since $1 - \\cos^2 B = \\sin^2 B$, $b^2 \\sin^2 B = -2ac \\cos B$.\n- Left side is positive, so right side must be positive: $-2ac \\cos B > 0$. Since $a, c > 0$, $\\cos B < 0$, so $B$ is obtuse. Wait, but the options include J. obtuse, but let\'s check the sign again.\n\nWait, from $b^2 = a^2 + c^2 - 2ac \\cos B$ and given $b^2 \\cos^2 B = a^2 + c^2$, so substitute $a^2 + c^2 = b^2 \\cos^2 B$ into law of cosines: $b^2 = b^2 \\cos^2 B - 2ac \\cos B$.\n\nThen $b^2 - b^2 \\cos^2 B = -2ac \\cos B$ => $b^2 \\sin^2 B = -2ac \\cos B$.\n\nLeft side: $b^2 \\sin^2 B > 0$ (since $b > 0$, $\\sin B > 0$ for $0 < B < \\pi$).\n\nRight side: $-2ac \\cos B$. Since $a, c > 0$, $-2ac < 0$, so for the right side to be positive, $\\cos B < 0$. Therefore, $B$ is obtuse. So answer is J.\n\nBut let\'s see the options: J is "obtuse". The problem says "then B is", and options include J. obtuse.\n\nWait, but let\'s check if B can be obtuse. Suppose B is obtuse, then cos B < 0. Given equation: $b^2 \\cos^2 B = a^2 + c^2$. Since cos^2 B is positive, left side is positive, which is good. But from the derivation, we have $b^2 \\sin^2 B = -2ac \\cos B > 0$, which holds because cos B < 0.\n\nWait, but let\'s test with a specific angle. Suppose B = 2π/3 (obtuse). Then cos B = -1/2, cos^2 B = 1/4.\n\nLaw of cosines: b^2 = a^2 + c^2 - 2ac*(-1/2) = a^2 + c^2 + ac.\n\nGiven equation: b^2*(1/4) = a^2 + c^2 => b^2 = 4(a^2 + c^2).\n\nSo 4(a^2 + c^2) = a^2 + c^2 + ac => 3(a^2 + c^2) = ac.\n\nBut 3(a^2 + c^2) >= 3*2ac = 6ac > ac (since ac > 0), so no solution for B=2π/3.\n\nWait, that\'s a problem. So my earlier conclusion that B is obtuse is wrong because the equation 3(a^2 + c^2) = ac has no solution (left side >= 6ac > ac).\n\nSo where did I go wrong?\n\nLet\'s start over.\n\nGiven: $b^2 \\cos^2 B = a^2 + c^2$ (1)\n\nLaw of cosines: $b^2 = a^2 + c^2 - 2ac \\cos B$ (2)\n\nFrom (1), $a^2 + c^2 = b^2 \\cos^2 B$. Plug into (2):\n\n$b^2 = b^2 \\cos^2 B - 2ac \\cos B$\n\nRearrange: $b^2 (1 - \\cos^2 B) = -2ac \\cos B$\n\n$b^2 \\sin^2 B = -2ac \\cos B$ (3)\n\nNow, left side: $b^2 \\sin^2 B > 0$ (since b > 0, 0 < B < π, so sin B > 0)\n\nRight side: $-2ac \\cos B$. Since a, c > 0, -2ac < 0. Therefore, for right side to be positive, cos B < 0. So B is obtuse.\n\nBut when I tested B=2π/3, it didn\'t work. Why?\n\nBecause for B obtuse, cos B < 0, but the equation (3) must hold. Let\'s take B such that cos B = -k, k > 0.\n\nThen (3): $b^2 \\sin^2 B = 2ac k$.\n\nFrom law of sines: a = 2R sin A, c = 2R sin C, b = 2R sin B.\n\nSo (3): (4R^2 sin^2 B) = 2*(4R^2 sin A sin C)*k => sin^2 B = 2 sin A sin C k.\n\nBut k = -cos B, so sin^2 B = -2 sin A sin C cos B.\n\nAlso, A + C = π - B, so C = π - B - A.\n\nLet\'s assume B is fixed, say B = 2π/3, then A + C = π/3.\n\nsin^2(2π/3) = (3/4) = -2 sin A sin C cos(2π/3) = -2 sin A sin C*(-1/2) = sin A sin C.\n\nSo 3/4 = sin A sin C.\n\nBut A + C = π/3, so sin A sin C = [cos(A - C) - cos(A + C)]/2 = [cos(A - C) - cos(π/3)]/2 = [cos(A - C) - 1/2]/2.\n\nSo 3/4 = [cos(A - C) - 1/2]/2 => 3/2 = cos(A - C) - 1/2 => cos(A - C) = 2.\n\nBut cos(A - C) <= 1, so impossible. Hence, no solution for B=2π/3.\n\nSo my initial conclusion that B is obtuse is incorrect because the equation has no solution for obtuse B? Wait, but the problem states "if b^2 cos^2 B = a^2 + c^2", so we need to find B such that this equation holds for some triangle.\n\nSo let\'s solve for B.\n\nFrom (3): $b^2 \\sin^2 B = -2ac \\cos B$.\n\nFrom law of sines, $a = 2R \\sin A$, $c = 2R \\sin C$, so $ac = 4R^2 \\sin A \\sin C$.\n\nAlso, $b = 2R \\sin B$, so $b^2 = 4R^2 \\sin^2 B$.\n\nPlug into (3): $4R^2 \\sin^2 B \\cdot \\sin^2 B = -2 \\cdot 4R^2 \\sin A \\sin C \\cdot \\cos B$.\n\nSimplify: $4R^2 \\sin^4 B = -8R^2 \\sin A \\sin C \\cos B$.\n\nDivide both sides by 4R^2: $\\sin^4 B = -2 \\sin A \\sin C \\cos B$.\n\nSince A + C = π - B, $\\sin A \\sin C = [\\cos(A - C) - \\cos(A + C)]/2 = [\\cos(A - C) + \\cos B]/2$.\n\nSo: $\\sin^4 B = -2 \\cdot [\\cos(A - C) + \\cos B]/2 \\cdot \\cos B = -[\\cos(A - C) + \\cos B] \\cos B$.\n\nThus: $\\sin^4 B = -\\cos(A - C) \\cos B - \\cos^2 B$.\n\nRearrange: $\\cos(A - C) \\cos B = -\\sin^4 B - \\cos^2 B$.\n\nLeft side: $\\cos(A - C) \\cos B$. Since $|A - C| < \\pi$ (as A and C are angles in a triangle), $\\cos(A - C) \\leq 1$ and $\\cos B$ is a real number.\n\nRight side: $-\\sin^4 B - \\cos^2 B = - (1 - \\cos^2 B)^2 - \\cos^2 B = - (1 - 2\\cos^2 B + \\cos^4 B) - \\cos^2 B = -1 + 2\\cos^2 B - \\cos^4 B - \\cos^2 B = -1 + \\cos^2 B - \\cos^4 B$.\n\nLet $x = \\cos^2 B$, so right side = $-1 + x - x^2$.\n\nLeft side: $\\cos(A - C) \\cos B$. Since $|\\cos(A - C)| \\leq 1$, and $\\cos B$ is real, the maximum of left side is $| \\cos B |$ (when $\\cos(A - C) = \\pm 1$).\n\nSo we have $| \\cos B | \\geq -1 + \\cos^2 B - \\cos^4 B$.\n\nLet $f(x) = -1 + x - x^2$ for $x = \\cos^2 B \\in (0,1]$ (since B is an angle in a triangle, 0 < B < π, so x ∈ (0,1]).\n\nWe need $| \\cos B | \\geq f(x)$. Since $x = \\cos^2 B$, $| \\cos B | = \\sqrt{x}$.\n\nSo inequality: $\\sqrt{x} \\geq -1 + x - x^2$.\n\nLet $g(x) = -1 + x - x^2 - \\sqrt{x}$. We need $g(x) \\leq 0$.\n\nTest x=1: g(1) = -1 + 1 - 1 - 1 = -2 ≤ 0.\n\nx=1/2: g(1/2) = -1 + 1/2 - 1/4 - √(1/2) = -0.75 - 0.707 ≈ -1.457 ≤ 0.\n\nx=0.25: g(0.25) = -1 + 0.25 - 0.0625 - 0.5 = -1.3125 ≤ 0.\n\nx approaching 0: g(x) ≈ -1 + 0 - 0 - 0 = -1 ≤ 0.\n\nSo the inequality holds for all x ∈ (0,1]. But we need to find B such that the original equation holds.\n\nWait, maybe another approach: use the given equation and law of cosines to express in terms of B.\n\nFrom (1): $a^2 + c^2 = b^2 \\cos^2 B$.\n\nFrom law of cosines: $b^2 = a^2 + c^2 - 2ac \\cos B = b^2 \\cos^2 B - 2ac \\cos B$.\n\nSo $b^2 (1 - \\cos^2 B) = -2ac \\cos B$ => $b^2 \\sin^2 B = -2ac \\cos B$.\n\nNow, by the AM ≥ GM inequality, $a^2 + c^2 \\geq 2ac$, so from (1), $b^2 \\cos^2 B \\geq 2ac$.\n\nFrom the previous equation, $ac = - (b^2 \\sin^2 B)/(2 \\cos B)$.\n\nSubstitute into AM ≥ GM: $b^2 \\cos^2 B \\geq 2 \\cdot (b^2 \\sin^2 B)/(2 \\cos B) = b^2 \\sin^2 B / \\cos B$.\n\nAssuming $b^2 > 0$, divide both sides by $b^2$: $\\cos^2 B \\geq \\sin^2 B / \\cos B$.\n\nMultiply both sides by $\\cos B$ (we need to consider the sign of cos B):\n\nCase 1: cos B > 0 (B acute). Then inequality becomes $\\cos^3 B \\geq \\sin^2 B = 1 - \\cos^2 B$.\n\nSo $\\cos^3 B + \\cos^2 B - 1 \\geq 0$.\n\nLet h(θ) = cos^3 θ + cos^2 θ - 1 for θ ∈ (0, π/2).\n\nh(0) = 0 + 1 - 1 = 0.\n\nh(π/2) = 0 + 0 - 1 = -1.\n\nh\'(θ) = -3 cos^2 θ sin θ - 2 cos θ sin θ = -sin θ cos θ (3 cos θ + 2) < 0 for θ ∈ (0, π/2).\n\nSo h(θ) is decreasing from 0 to -1, so h(θ) < 0 for θ ∈ (0, π/2). Thus, no solution for B acute.\n\nCase 2: cos B < 0 (B obtuse). Then multiplying by cos B reverses inequality: $\\cos^3 B \\leq \\sin^2 B = 1 - \\cos^2 B$.\n\nSo $\\cos^3 B + \\cos^2 B - 1 \\leq 0$.\n\nLet θ = B, obtuse, so θ ∈ (π/2, π), cos θ ∈ (-1, 0).\n\nLet x = cos θ, x ∈ (-1, 0).\n\nInequality: x^3 + x^2 - 1 ≤ 0.\n\nAt x = -1: (-1)^3 + (-1)^2 - 1 = -1 + 1 - 1 = -1 ≤ 0.\n\nAt x = 0: 0 + 0 - 1 = -1 ≤ 0.\n\nDerivative: 3x^2 + 2x = x(3x + 2). Critical points at x=0 (not in (-1,0)) and x=-2/3.\n\nAt x=-2/3: (-8/27) + (4/9) - 1 = (-8/27 + 12/27) - 1 = 4/27 - 1 = -23/27 ≤ 0.\n\nSo x^3 + x^2 - 1 ≤ 0 for all x ∈ (-1, 0). So the inequality holds for all obtuse B?\n\nBut earlier test with B=2π/3 didn\'t work. What\'s the issue?\n\nWait, in the AM ≥ GM step, we have $a^2 + c^2 \\geq 2ac$, so $b^2 \\cos^2 B \\geq 2ac$. But from the equation, $ac = - (b^2 \\sin^2 B)/(2 \\cos B)$. Since B is obtuse, cos B < 0, so -cos B > 0, so ac > 0, which is good.\n\nLet\'s take B = π/2 (right angle). Then cos B = 0, but given equation: b^2 * 0 = a^2',

In [25]:
comparison_rows = []

if "baseline1_val_result" in globals():
    comparison_rows.append({
        "baseline": "baseline1",
        **baseline1_val_result.report["summary"],
    })

comparison_rows.append({
    "baseline": "baseline2",
    **baseline2_val_result.report["summary"],
    "schema_valid_rate": baseline2_val_result.report["formatting"]["schema_valid_rate"],
    "extractable_rate": baseline2_val_result.report["formatting"]["extractable_rate"],
    "retry_rate": baseline2_val_result.report["formatting"]["retry_rate"],
})

pd.DataFrame(comparison_rows)

,baseline,n_scored,overall_acc,mcq_acc,free_form_acc,n_mcq,n_free_form,n_correct,schema_valid_rate,extractable_rate,retry_rate
0,baseline2,225,0.515556,0.426667,0.56,75,150,116,0.835556,0.88,0.2

# Baseline 3: Prompt Engineering

# Baseline 4: Supervised Fine-Tuning (SFT)

## Post-SFT Tuning

# Baseline 5: RL